# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.user import User


class ListUserResponse(UniversalBaseModel):
    users: typing.Optional[typing.List[User]] = pydantic.Field(default=None)
    """
    Principal entries. In directory mode every entry is an active workspace member.
    """

    next_cursor: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="nextCursor"),
        pydantic.Field(alias="nextCursor", description="Pagination cursor for fetching the next page of results"),
    ] = None
    """
    Pagination cursor for fetching the next page of results
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
