# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawStoryClient, RawStoryClient
from .types.post_story_response import PostStoryResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StoryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStoryClient
        """
        return self._raw_client

    def post(
        self,
        *,
        asset_id: str,
        caption: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostStoryResponse:
        """
        Posts a story to your Roam. Stories are short photo or video updates that appear
        above your profile picture for your teammates, and expire 24 hours after posting.

        ## Posting Flow

        1. Create the media asset with [asset.create](https://developer.ro.am/docs/api/asset-create) using
           `purpose: "story"`, and upload the file bytes using the returned upload instructions.
        2. Call this endpoint with the `assetId` (and an optional `caption`).

        The media must be a photo or a video (videos up to 2.5 minutes; media is optimized
        to portrait 1080×1920). If the upload is still processing — typical for videos in
        the first seconds after upload — this endpoint returns a 400 with a "still
        processing" message; retry after a short delay.

        The media must outlive the story's 24-hour lifetime, so post within about 23 hours
        of creating the asset (story assets expire about 48 hours after creation); older
        assets are rejected and must be recreated.

        **Access:** Personal only. Stories are always posted as the authenticated user —
        a story appears above *your* profile picture, and there is no bot persona surface
        for stories — so organization tokens are rejected.

        **Required scope:** `chat:send_message` or `chat:write` (the same permission that
        gates sending a chat message)

        Parameters
        ----------
        asset_id : str
            ID of a processed asset created via [asset.create](https://developer.ro.am/docs/api/asset-create)
            with `purpose: "story"`. The asset must be owned by the authenticated user.

        caption : typing.Optional[str]
            Optional caption displayed with the story.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostStoryResponse
            The story was posted.

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.story.post(
            asset_id="019be84b-0fa8-788f-8850-96de4cc39130",
            caption="Greetings from the offsite 👋",
        )
        """
        _response = self._raw_client.post(asset_id=asset_id, caption=caption, request_options=request_options)
        return _response.data


class AsyncStoryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStoryClient
        """
        return self._raw_client

    async def post(
        self,
        *,
        asset_id: str,
        caption: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostStoryResponse:
        """
        Posts a story to your Roam. Stories are short photo or video updates that appear
        above your profile picture for your teammates, and expire 24 hours after posting.

        ## Posting Flow

        1. Create the media asset with [asset.create](https://developer.ro.am/docs/api/asset-create) using
           `purpose: "story"`, and upload the file bytes using the returned upload instructions.
        2. Call this endpoint with the `assetId` (and an optional `caption`).

        The media must be a photo or a video (videos up to 2.5 minutes; media is optimized
        to portrait 1080×1920). If the upload is still processing — typical for videos in
        the first seconds after upload — this endpoint returns a 400 with a "still
        processing" message; retry after a short delay.

        The media must outlive the story's 24-hour lifetime, so post within about 23 hours
        of creating the asset (story assets expire about 48 hours after creation); older
        assets are rejected and must be recreated.

        **Access:** Personal only. Stories are always posted as the authenticated user —
        a story appears above *your* profile picture, and there is no bot persona surface
        for stories — so organization tokens are rejected.

        **Required scope:** `chat:send_message` or `chat:write` (the same permission that
        gates sending a chat message)

        Parameters
        ----------
        asset_id : str
            ID of a processed asset created via [asset.create](https://developer.ro.am/docs/api/asset-create)
            with `purpose: "story"`. The asset must be owned by the authenticated user.

        caption : typing.Optional[str]
            Optional caption displayed with the story.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostStoryResponse
            The story was posted.

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.story.post(
                asset_id="019be84b-0fa8-788f-8850-96de4cc39130",
                caption="Greetings from the offsite 👋",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post(asset_id=asset_id, caption=caption, request_options=request_options)
        return _response.data
