# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.method_not_allowed_error import MethodNotAllowedError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error import Error
from .types.post_story_response import PostStoryResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawStoryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def post(
        self,
        *,
        asset_id: str,
        caption: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PostStoryResponse]:
        """
        Posts a story to your Roam. Stories are short photo or video updates that appear
        above your profile picture for your teammates, and expire 24 hours after posting.

        ## Posting Flow

        1. Create the media asset with [asset.create](https://developer.ro.am/docs/api/asset-create) using
           `purpose: "story"`, and upload the file bytes using the returned upload instructions.
        2. Call this endpoint with the `assetId` (and an optional `caption`).

        The media must be a photo or a video (videos up to 2.5 minutes; media is optimized
        to portrait 1080×1920). If the upload is still processing — typical for videos in
        the first seconds after upload — this endpoint returns a 400 with a "still
        processing" message; retry after a short delay.

        The media must outlive the story's 24-hour lifetime, so post within about 23 hours
        of creating the asset (story assets expire about 48 hours after creation); older
        assets are rejected and must be recreated.

        **Access:** Personal only. Stories are always posted as the authenticated user —
        a story appears above *your* profile picture, and there is no bot persona surface
        for stories — so organization tokens are rejected.

        **Required scope:** `chat:send_message` or `chat:write` (the same permission that
        gates sending a chat message)

        Parameters
        ----------
        asset_id : str
            ID of a processed asset created via [asset.create](https://developer.ro.am/docs/api/asset-create)
            with `purpose: "story"`. The asset must be owned by the authenticated user.

        caption : typing.Optional[str]
            Optional caption displayed with the story.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PostStoryResponse]
            The story was posted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "story.post",
            method="POST",
            json={
                "assetId": asset_id,
                "caption": caption,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostStoryResponse,
                    parse_obj_as(
                        type_=PostStoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawStoryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def post(
        self,
        *,
        asset_id: str,
        caption: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PostStoryResponse]:
        """
        Posts a story to your Roam. Stories are short photo or video updates that appear
        above your profile picture for your teammates, and expire 24 hours after posting.

        ## Posting Flow

        1. Create the media asset with [asset.create](https://developer.ro.am/docs/api/asset-create) using
           `purpose: "story"`, and upload the file bytes using the returned upload instructions.
        2. Call this endpoint with the `assetId` (and an optional `caption`).

        The media must be a photo or a video (videos up to 2.5 minutes; media is optimized
        to portrait 1080×1920). If the upload is still processing — typical for videos in
        the first seconds after upload — this endpoint returns a 400 with a "still
        processing" message; retry after a short delay.

        The media must outlive the story's 24-hour lifetime, so post within about 23 hours
        of creating the asset (story assets expire about 48 hours after creation); older
        assets are rejected and must be recreated.

        **Access:** Personal only. Stories are always posted as the authenticated user —
        a story appears above *your* profile picture, and there is no bot persona surface
        for stories — so organization tokens are rejected.

        **Required scope:** `chat:send_message` or `chat:write` (the same permission that
        gates sending a chat message)

        Parameters
        ----------
        asset_id : str
            ID of a processed asset created via [asset.create](https://developer.ro.am/docs/api/asset-create)
            with `purpose: "story"`. The asset must be owned by the authenticated user.

        caption : typing.Optional[str]
            Optional caption displayed with the story.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PostStoryResponse]
            The story was posted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "story.post",
            method="POST",
            json={
                "assetId": asset_id,
                "caption": caption,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PostStoryResponse,
                    parse_obj_as(
                        type_=PostStoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
