# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from __future__ import annotations

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_link_meeting_response import CreateLinkMeetingResponse
    from .info_meeting_response import InfoMeetingResponse
    from .info_meeting_response_chapters_item import InfoMeetingResponseChaptersItem
    from .info_meeting_response_video_status import InfoMeetingResponseVideoStatus
    from .link_info_meeting_response import LinkInfoMeetingResponse
    from .list_meeting_response import ListMeetingResponse
    from .list_meeting_response_meetings_item import ListMeetingResponseMeetingsItem
    from .list_meeting_response_meetings_item_chapters_item import ListMeetingResponseMeetingsItemChaptersItem
    from .list_meeting_response_meetings_item_video_status import ListMeetingResponseMeetingsItemVideoStatus
    from .participants_meeting_response import ParticipantsMeetingResponse
    from .prompt_meeting_response import PromptMeetingResponse
    from .search_meeting_response import SearchMeetingResponse
    from .search_meeting_response_inferred_filter import SearchMeetingResponseInferredFilter
    from .search_meeting_response_results_item import SearchMeetingResponseResultsItem
    from .share_link_meeting_response import ShareLinkMeetingResponse
    from .transcript_meeting_response import TranscriptMeetingResponse
    from .transcript_meeting_response_cues_item import TranscriptMeetingResponseCuesItem
_dynamic_imports: typing.Dict[str, str] = {
    "CreateLinkMeetingResponse": ".create_link_meeting_response",
    "InfoMeetingResponse": ".info_meeting_response",
    "InfoMeetingResponseChaptersItem": ".info_meeting_response_chapters_item",
    "InfoMeetingResponseVideoStatus": ".info_meeting_response_video_status",
    "LinkInfoMeetingResponse": ".link_info_meeting_response",
    "ListMeetingResponse": ".list_meeting_response",
    "ListMeetingResponseMeetingsItem": ".list_meeting_response_meetings_item",
    "ListMeetingResponseMeetingsItemChaptersItem": ".list_meeting_response_meetings_item_chapters_item",
    "ListMeetingResponseMeetingsItemVideoStatus": ".list_meeting_response_meetings_item_video_status",
    "ParticipantsMeetingResponse": ".participants_meeting_response",
    "PromptMeetingResponse": ".prompt_meeting_response",
    "SearchMeetingResponse": ".search_meeting_response",
    "SearchMeetingResponseInferredFilter": ".search_meeting_response_inferred_filter",
    "SearchMeetingResponseResultsItem": ".search_meeting_response_results_item",
    "ShareLinkMeetingResponse": ".share_link_meeting_response",
    "TranscriptMeetingResponse": ".transcript_meeting_response",
    "TranscriptMeetingResponseCuesItem": ".transcript_meeting_response_cues_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateLinkMeetingResponse",
    "InfoMeetingResponse",
    "InfoMeetingResponseChaptersItem",
    "InfoMeetingResponseVideoStatus",
    "LinkInfoMeetingResponse",
    "ListMeetingResponse",
    "ListMeetingResponseMeetingsItem",
    "ListMeetingResponseMeetingsItemChaptersItem",
    "ListMeetingResponseMeetingsItemVideoStatus",
    "ParticipantsMeetingResponse",
    "PromptMeetingResponse",
    "SearchMeetingResponse",
    "SearchMeetingResponseInferredFilter",
    "SearchMeetingResponseResultsItem",
    "ShareLinkMeetingResponse",
    "TranscriptMeetingResponse",
    "TranscriptMeetingResponseCuesItem",
]
