# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.action_item import ActionItem
from ...types.meeting_participant import MeetingParticipant
from .list_meeting_response_meetings_item_chapters_item import ListMeetingResponseMeetingsItemChaptersItem
from .list_meeting_response_meetings_item_video_status import ListMeetingResponseMeetingsItemVideoStatus


class ListMeetingResponseMeetingsItem(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Meeting ID
    """

    title: str = pydantic.Field()
    """
    Meeting title
    """

    subtitle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Meeting subtitle
    """

    start: dt.datetime = pydantic.Field()
    """
    Meeting start time (RFC-3339)
    """

    participant_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="participantCount"),
        pydantic.Field(alias="participantCount", description="Total number of participants"),
    ]
    """
    Total number of participants
    """

    has_video: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="hasVideo"),
        pydantic.Field(
            alias="hasVideo",
            description="Whether the meeting was video recorded — a video track\nexists. `true` from the moment recording starts and it\nnever flips back. It does **not** mean the recording is\nready to fetch or play; read `videoStatus` for that.\nMatches [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info) and\nthe `meeting.ended` webhook `data.hasVideo`.",
        ),
    ]
    """
    Whether the meeting was video recorded — a video track
    exists. `true` from the moment recording starts and it
    never flips back. It does **not** mean the recording is
    ready to fetch or play; read `videoStatus` for that.
    Matches [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info) and
    the `meeting.ended` webhook `data.hasVideo`.
    """

    video_status: typing_extensions.Annotated[
        ListMeetingResponseMeetingsItemVideoStatus,
        FieldMetadata(alias="videoStatus"),
        pydantic.Field(
            alias="videoStatus",
            description="Where this meeting's video recording is, which — unlike\n`hasVideo` — changes over time:\n\n- `none` — no video track; the meeting was not recorded.\n  Always paired with `hasVideo: false`.\n- `processing` — a recording exists but its upload has\n  not finished, so there is nothing to play yet. List\n  again shortly, or call\n  [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info) for that one\n  meeting.\n- `available` — the recording is uploaded and has an\n  asset. Use\n  [`/meeting.shareLink`](https://developer.ro.am/docs/api/meeting-share-link)\n  to get a shareable link to it.",
        ),
    ]
    """
    Where this meeting's video recording is, which — unlike
    `hasVideo` — changes over time:
    
    - `none` — no video track; the meeting was not recorded.
      Always paired with `hasVideo: false`.
    - `processing` — a recording exists but its upload has
      not finished, so there is nothing to play yet. List
      again shortly, or call
      [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info) for that one
      meeting.
    - `available` — the recording is uploaded and has an
      asset. Use
      [`/meeting.shareLink`](https://developer.ro.am/docs/api/meeting-share-link)
      to get a shareable link to it.
    """

    host: typing.Optional[MeetingParticipant] = pydantic.Field(default=None)
    """
    Meeting host as a participant object. Requires
    `user:read` scope; emails are only included with
    `user:read.email`. Omitted when the host cannot be
    resolved.
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    AI-generated meeting summary. Only present when `expand=summary`.
    """

    action_items: typing_extensions.Annotated[
        typing.Optional[typing.List[ActionItem]],
        FieldMetadata(alias="actionItems"),
        pydantic.Field(
            alias="actionItems", description="AI-extracted action items. Only present when `expand=actionItems`."
        ),
    ] = None
    """
    AI-extracted action items. Only present when `expand=actionItems`.
    """

    chapters: typing.Optional[typing.List[ListMeetingResponseMeetingsItemChaptersItem]] = pydantic.Field(default=None)
    """
    Meeting chapters/segments. Only present when `expand=chapters`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
