# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.meeting_participant import MeetingParticipant


class ParticipantsMeetingResponse(UniversalBaseModel):
    ok: typing.Optional[bool] = None
    participants: typing.List[MeetingParticipant]
    total: int = pydantic.Field()
    """
    Total number of participants in the meeting
    """

    next_cursor: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="nextCursor"),
        pydantic.Field(
            alias="nextCursor",
            description="Present when more participants remain. Pass as `cursor` on the next request. Omitted on the last page.",
        ),
    ] = None
    """
    Present when more participants remain. Pass as `cursor` on the next request. Omitted on the last page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
