# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .search_meeting_response_inferred_filter import SearchMeetingResponseInferredFilter
from .search_meeting_response_results_item import SearchMeetingResponseResultsItem


class SearchMeetingResponse(UniversalBaseModel):
    results: typing.Optional[typing.List[SearchMeetingResponseResultsItem]] = None
    inferred_filter: typing_extensions.Annotated[
        typing.Optional[SearchMeetingResponseInferredFilter],
        FieldMetadata(alias="inferredFilter"),
        pydantic.Field(alias="inferredFilter", description="AI-inferred search filters"),
    ] = None
    """
    AI-inferred search filters
    """

    inferred_query: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="inferredQuery"),
        pydantic.Field(alias="inferredQuery", description="AI-refined search query"),
    ] = None
    """
    AI-refined search query
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
