# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class RecordingListResponseRecordingsItem(UniversalBaseModel):
    recording_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="recordingId"),
        pydantic.Field(alias="recordingId", description="A unique identifier for the recording"),
    ] = None
    """
    A unique identifier for the recording
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the Roam room where the recording took place
    """

    start_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="startTime"),
        pydantic.Field(alias="startTime", description="Exact time when the recording began"),
    ] = None
    """
    Exact time when the recording began
    """

    end_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="endTime"),
        pydantic.Field(alias="endTime", description="Exact time when the recording stopped"),
    ] = None
    """
    Exact time when the recording stopped
    """

    video_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="videoUrl"),
        pydantic.Field(alias="videoUrl", description="URL where the video file may be downloaded"),
    ] = None
    """
    URL where the video file may be downloaded
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
