# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.user_audit_log import UserAuditLog


class ListUserAuditLogResponse(UniversalBaseModel):
    audit_logs: typing_extensions.Annotated[
        typing.Optional[typing.List[UserAuditLog]], FieldMetadata(alias="auditLogs"), pydantic.Field(alias="auditLogs")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
