# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostChatResponse(UniversalBaseModel):
    ok: typing.Optional[bool] = None
    chat_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="chatId"),
        pydantic.Field(alias="chatId", description="ID of the chat where the message was (or will be) posted"),
    ] = None
    """
    ID of the chat where the message was (or will be) posted
    """

    thread_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="threadTimestamp"),
        pydantic.Field(alias="threadTimestamp", description="Thread timestamp if replying to a thread"),
    ] = None
    """
    Thread timestamp if replying to a thread
    """

    timestamp: typing.Optional[int] = pydantic.Field(default=None)
    """
    Message timestamp (present if sync is set; omitted for scheduled posts)
    """

    scheduled_message_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="scheduledMessageId"),
        pydantic.Field(
            alias="scheduledMessageId",
            description="ID of the scheduled message (only when `sendAt` was provided). Pass to `/chat.scheduled.cancel` to cancel, or find it later via `/chat.scheduled.list`.",
        ),
    ] = None
    """
    ID of the scheduled message (only when `sendAt` was provided). Pass to `/chat.scheduled.cancel` to cancel, or find it later via `/chat.scheduled.list`.
    """

    send_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="sendAt"),
        pydantic.Field(
            alias="sendAt", description="Scheduled send time echoed from the request (only when `sendAt` was provided)"
        ),
    ] = None
    """
    Scheduled send time echoed from the request (only when `sendAt` was provided)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
