# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.address import Address
from ...types.chat_message import ChatMessage


class SearchChatResponse(UniversalBaseModel):
    messages: typing.List[ChatMessage]
    next_cursor: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="nextCursor"),
        pydantic.Field(
            alias="nextCursor", description="Cursor to fetch the next page. Absent when there are no more results."
        ),
    ] = None
    """
    Cursor to fetch the next page. Absent when there are no more results.
    """

    addresses: typing.Optional[typing.Dict[str, Address]] = pydantic.Field(default=None)
    """
    Resolved address objects keyed by ID, for the senders and
    mentioned entities in this response. Included only when
    `expand=addresses` is requested.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
