# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class StartStreamChatResponse(UniversalBaseModel):
    stream_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="streamId"),
        pydantic.Field(
            alias="streamId", description="Unique ID for this stream. Pass it to appendStream and stopStream."
        ),
    ] = None
    """
    Unique ID for this stream. Pass it to appendStream and stopStream.
    """

    chat_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="chatId"),
        pydantic.Field(alias="chatId", description="ID of the destination chat."),
    ] = None
    """
    ID of the destination chat.
    """

    thread_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="threadTimestamp"),
        pydantic.Field(alias="threadTimestamp", description="Thread timestamp if the stream is a thread reply."),
    ] = None
    """
    Thread timestamp if the stream is a thread reply.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
