# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMagicastsClient, RawMagicastsClient
from .types.magicast_share_link_response import MagicastShareLinkResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MagicastsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMagicastsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMagicastsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMagicastsClient
        """
        return self._raw_client

    def magicast_share_link(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MagicastShareLinkResponse:
        """
        Returns a shareable player URL for a Magicast. Pass the `id` obtained from
        [`/magicast.list`](https://developer.ro.am/docs/api/magicast-list) or
        [`/magicast.info`](https://developer.ro.am/docs/api/magicast-info).

        This endpoint is **get-or-create**: it returns the Magicast's existing
        share link, or mints one the first time it is called. Repeat calls for the
        same Magicast return the same URL.

        Creating a share link is a deliberate action, which is why it has its own
        endpoint rather than being returned as a field that is always present on
        `magicast.list` / `magicast.info`. Fetching a Magicast never mints a
        shareable link as a side effect. `magicast.info` includes `shareUrl` only
        when a link already exists.

        The URL is `https://ro.am/share/{key}`. There is no
        `https://ro.am/magicast/{id}` route.

        You can only create a share link for a Magicast you can access; the same
        access check as `magicast.info` applies.

        **Access:** Organization and Personal. Personal access tokens restrict to
        Magicasts owned by the authenticated user.

        **Required scope:** `magicast:read`

        Parameters
        ----------
        id : str
            The Magicast ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MagicastShareLinkResponse
            The Magicast's shareable link.

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.magicasts.magicast_share_link(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.magicast_share_link(id=id, request_options=request_options)
        return _response.data


class AsyncMagicastsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMagicastsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMagicastsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMagicastsClient
        """
        return self._raw_client

    async def magicast_share_link(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> MagicastShareLinkResponse:
        """
        Returns a shareable player URL for a Magicast. Pass the `id` obtained from
        [`/magicast.list`](https://developer.ro.am/docs/api/magicast-list) or
        [`/magicast.info`](https://developer.ro.am/docs/api/magicast-info).

        This endpoint is **get-or-create**: it returns the Magicast's existing
        share link, or mints one the first time it is called. Repeat calls for the
        same Magicast return the same URL.

        Creating a share link is a deliberate action, which is why it has its own
        endpoint rather than being returned as a field that is always present on
        `magicast.list` / `magicast.info`. Fetching a Magicast never mints a
        shareable link as a side effect. `magicast.info` includes `shareUrl` only
        when a link already exists.

        The URL is `https://ro.am/share/{key}`. There is no
        `https://ro.am/magicast/{id}` route.

        You can only create a share link for a Magicast you can access; the same
        access check as `magicast.info` applies.

        **Access:** Organization and Personal. Personal access tokens restrict to
        Magicasts owned by the authenticated user.

        **Required scope:** `magicast:read`

        Parameters
        ----------
        id : str
            The Magicast ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MagicastShareLinkResponse
            The Magicast's shareable link.

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.magicasts.magicast_share_link(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.magicast_share_link(id=id, request_options=request_options)
        return _response.data
