# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.method_not_allowed_error import MethodNotAllowedError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error import Error
from .types.magicast_share_link_response import MagicastShareLinkResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMagicastsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def magicast_share_link(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MagicastShareLinkResponse]:
        """
        Returns a shareable player URL for a Magicast. Pass the `id` obtained from
        [`/magicast.list`](https://developer.ro.am/docs/api/magicast-list) or
        [`/magicast.info`](https://developer.ro.am/docs/api/magicast-info).

        This endpoint is **get-or-create**: it returns the Magicast's existing
        share link, or mints one the first time it is called. Repeat calls for the
        same Magicast return the same URL.

        Creating a share link is a deliberate action, which is why it has its own
        endpoint rather than being returned as a field that is always present on
        `magicast.list` / `magicast.info`. Fetching a Magicast never mints a
        shareable link as a side effect. `magicast.info` includes `shareUrl` only
        when a link already exists.

        The URL is `https://ro.am/share/{key}`. There is no
        `https://ro.am/magicast/{id}` route.

        You can only create a share link for a Magicast you can access; the same
        access check as `magicast.info` applies.

        **Access:** Organization and Personal. Personal access tokens restrict to
        Magicasts owned by the authenticated user.

        **Required scope:** `magicast:read`

        Parameters
        ----------
        id : str
            The Magicast ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MagicastShareLinkResponse]
            The Magicast's shareable link.
        """
        _response = self._client_wrapper.httpx_client.request(
            "magicast.shareLink",
            method="POST",
            json={
                "id": id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MagicastShareLinkResponse,
                    parse_obj_as(
                        type_=MagicastShareLinkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMagicastsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def magicast_share_link(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MagicastShareLinkResponse]:
        """
        Returns a shareable player URL for a Magicast. Pass the `id` obtained from
        [`/magicast.list`](https://developer.ro.am/docs/api/magicast-list) or
        [`/magicast.info`](https://developer.ro.am/docs/api/magicast-info).

        This endpoint is **get-or-create**: it returns the Magicast's existing
        share link, or mints one the first time it is called. Repeat calls for the
        same Magicast return the same URL.

        Creating a share link is a deliberate action, which is why it has its own
        endpoint rather than being returned as a field that is always present on
        `magicast.list` / `magicast.info`. Fetching a Magicast never mints a
        shareable link as a side effect. `magicast.info` includes `shareUrl` only
        when a link already exists.

        The URL is `https://ro.am/share/{key}`. There is no
        `https://ro.am/magicast/{id}` route.

        You can only create a share link for a Magicast you can access; the same
        access check as `magicast.info` applies.

        **Access:** Organization and Personal. Personal access tokens restrict to
        Magicasts owned by the authenticated user.

        **Required scope:** `magicast:read`

        Parameters
        ----------
        id : str
            The Magicast ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MagicastShareLinkResponse]
            The Magicast's shareable link.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "magicast.shareLink",
            method="POST",
            json={
                "id": id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MagicastShareLinkResponse,
                    parse_obj_as(
                        type_=MagicastShareLinkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
