# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMeetingClient, RawMeetingClient
from .types.create_link_meeting_response import CreateLinkMeetingResponse
from .types.info_meeting_response import InfoMeetingResponse
from .types.link_info_meeting_response import LinkInfoMeetingResponse
from .types.list_meeting_response import ListMeetingResponse
from .types.participants_meeting_response import ParticipantsMeetingResponse
from .types.prompt_meeting_response import PromptMeetingResponse
from .types.search_meeting_response import SearchMeetingResponse
from .types.share_link_meeting_response import ShareLinkMeetingResponse
from .types.transcript_meeting_response import TranscriptMeetingResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MeetingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMeetingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMeetingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMeetingClient
        """
        return self._raw_client

    def list(
        self,
        *,
        before: typing.Optional[dt.datetime] = None,
        after: typing.Optional[dt.datetime] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        expand: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMeetingResponse:
        """
        List meetings, ordered newest-first.

        **Access:** Organization and Personal. Personal tokens return meetings the
        authenticated user participated in. Organization tokens return every meeting
        in the Roam only with [`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread);
        without it, results are limited to meetings the install's bot has access to.

        **Required scope:** `meetings:read` (add `admin:meetings:read` for roam-wide org access)

        Parameters
        ----------
        before : typing.Optional[dt.datetime]
            Only return meetings that started before this time (RFC-3339). Sub-millisecond precision is truncated.

        after : typing.Optional[dt.datetime]
            Only return meetings that started after this time (RFC-3339). Sub-millisecond precision is truncated.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        limit : typing.Optional[int]
            Number of meetings to return per page. Capped to **10** when
            `expand` includes `summary`, `actionItems`, or `chapters`, since
            expanded payloads are substantially larger.

        expand : typing.Optional[str]
            Comma-separated list of fields to inline on each meeting. Allowed
            values are `summary`, `actionItems`, and `chapters` — same shape
            as on [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info). Use this to
            avoid N+1 follow-up calls when scanning many recent meetings.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMeetingResponse
            Meetings retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.list()
        """
        _response = self._raw_client.list(
            before=before, after=after, cursor=cursor, limit=limit, expand=expand, request_options=request_options
        )
        return _response.data

    def info(
        self,
        *,
        id: str,
        max_participants: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InfoMeetingResponse:
        """
        Get detailed information about a specific meeting, including AI-generated summary, action items, and chapters.

        Participants are included inline up to the `maxParticipants` limit. For meetings with more participants, use [`/meeting.participants`](https://developer.ro.am/docs/api/meeting-participants) to paginate through the full list.

        **Access:** Organization and Personal. Personal tokens are limited to meetings
        the authenticated user participated in. Organization tokens without
        [`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread)
        are limited to meetings the install's bot has access to.

        **Required scope:** `meetings:read` (add `admin:meetings:read` for roam-wide org access; add `user:read` to include participants, `user:read.email` for participant emails)

        Parameters
        ----------
        id : str
            The meeting ID.

        max_participants : typing.Optional[int]
            Maximum number of participants to resolve and include inline. Use `/meeting.participants` for full pagination.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InfoMeetingResponse
            Meeting info retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.info(
            id="id",
        )
        """
        _response = self._raw_client.info(id=id, max_participants=max_participants, request_options=request_options)
        return _response.data

    def participants(
        self,
        *,
        id: str,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ParticipantsMeetingResponse:
        """
        Paginate through all participants of a meeting. This is the dedicated endpoint for retrieving the full participant list, complementing the capped inline participants in [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info).

        Pagination uses an **opaque cursor** (not a row offset). Pass `nextCursor`
        from a previous response as `cursor` to fetch the next page. Invalid cursors
        return `error: "invalid_cursor"` — see [Responses and Errors](https://developer.ro.am/docs/guides/responses-and-errors).

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read` and `user:read` (add `user:read.email` for participant emails)

        Parameters
        ----------
        id : str
            The meeting ID.

        limit : typing.Optional[int]
            Number of participants to return per page (default 50, max 200).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not parse or construct cursors yourself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ParticipantsMeetingResponse
            Participants retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.participants(
            id="id",
        )
        """
        _response = self._raw_client.participants(id=id, limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def transcript(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TranscriptMeetingResponse:
        """
        Retrieve the transcript for a meeting.

        Supports content negotiation:
        - **JSON** (default): Returns structured transcript with cues containing speaker IDs, text, and timing
        - **WebVTT**: Set `Accept: text/vtt` header to receive standard WebVTT format with speaker voice tags

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read`

        **Errors** (see [Responses and Errors](https://developer.ro.am/docs/guides/responses-and-errors)):

        | `error` code | Meaning |
        |--------------|---------|
        | `meeting_not_found` | Unknown or inaccessible meeting |
        | `transcript_pending` | Not ready yet — retry later (may include `Retry-After`) |
        | `transcript_unavailable` | Meeting was not transcribed — stop retrying |
        | `upstream_timeout` | Timed out waiting on an upstream service — retry |

        Parameters
        ----------
        id : str
            The meeting ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranscriptMeetingResponse
            Transcript retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.transcript(
            id="id",
        )
        """
        _response = self._raw_client.transcript(id=id, request_options=request_options)
        return _response.data

    def search(
        self,
        *,
        query: str,
        after: typing.Optional[dt.date] = None,
        before: typing.Optional[dt.date] = None,
        timezone: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchMeetingResponse:
        """
        AI-powered search across meeting transcripts and summaries.

        **Access:** Personal access only. Organization (account-level) tokens are not supported.

        **Required scope:** `meetings:read`

        Parameters
        ----------
        query : str
            Search query string.

        after : typing.Optional[dt.date]
            Only return results from meetings after this date (YYYY-MM-DD).

        before : typing.Optional[dt.date]
            Only return results from meetings before this date (YYYY-MM-DD).

        timezone : typing.Optional[str]
            Timezone for date interpretation (e.g. "America/New_York").

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchMeetingResponse
            Search results retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.search(
            query="query",
        )
        """
        _response = self._raw_client.search(
            query=query, after=after, before=before, timezone=timezone, request_options=request_options
        )
        return _response.data

    def prompt(
        self, *, id: str, prompt: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PromptMeetingResponse:
        """
        Ask an AI question about a meeting's transcript content. Returns a natural language response based on the meeting transcript.

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read`

        Parameters
        ----------
        id : str
            The meeting ID.

        prompt : str
            The question to ask about the meeting.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PromptMeetingResponse
            Response generated successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.prompt(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            prompt="What action items were assigned to Alex?",
        )
        """
        _response = self._raw_client.prompt(id=id, prompt=prompt, request_options=request_options)
        return _response.data

    def share_link(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ShareLinkMeetingResponse:
        """
        Returns a shareable URL for a meeting that you can distribute to others. Pass the `id` of a meeting obtained from [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) or [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info).

        This endpoint is **get-or-create**: it returns the meeting's existing share link, or mints one the first time it is called for that meeting. Repeat calls for the same meeting return the same URL.

        Creating a share link is a deliberate action, which is why it has its own endpoint rather than being returned as a field on `meeting.list` / `meeting.info` — fetching a meeting never mints a shareable link as a side effect. You can only create a share link for a meeting you can access; the same access check as `meeting.info` applies.

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read`

        Parameters
        ----------
        id : str
            The meeting ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShareLinkMeetingResponse
            The meeting's shareable link.

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.share_link(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.share_link(id=id, request_options=request_options)
        return _response.data

    def create_link(
        self,
        *,
        name: str,
        host: typing.Optional[str] = OMIT,
        start: typing.Optional[dt.datetime] = OMIT,
        end: typing.Optional[dt.datetime] = OMIT,
        require_unconfirmed_email: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateLinkMeetingResponse:
        """
        Create a meeting link.

        **Access:** Organization and Personal. In Organization mode, specify the host by email. In Personal mode, the host defaults to the authenticated user.

        **Required scope:** `meeting:write` or `meetinglink:write`

        Parameters
        ----------
        name : str
            Meeting Name

        host : typing.Optional[str]
            Meeting Host Email, matching a member of your Roam.

            Required for Organization tokens. For Personal tokens, this is optional and defaults to the authenticated user. If provided with a Personal token, it must match the authenticated user's email.

        start : typing.Optional[dt.datetime]
            (Optional) Meeting start time in RFC3339.

        end : typing.Optional[dt.datetime]
            (Optional) Meeting end time in RFC3339.

        require_unconfirmed_email : typing.Optional[bool]
            (Optional) If true, guests must verify ownership of their email address before joining.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateLinkMeetingResponse
            Meeting link successfully created

        Examples
        --------
        import datetime

        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.create_link(
            name="Q1 Planning Session",
            host="alex.chen@example.com",
            start=datetime.datetime.fromisoformat(
                "2026-02-15 14:00:00+00:00",
            ),
            end=datetime.datetime.fromisoformat(
                "2026-02-15 15:00:00+00:00",
            ),
        )
        """
        _response = self._raw_client.create_link(
            name=name,
            host=host,
            start=start,
            end=end,
            require_unconfirmed_email=require_unconfirmed_email,
            request_options=request_options,
        )
        return _response.data

    def link_info(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> LinkInfoMeetingResponse:
        """
        Get a meeting link.

        **Access:** Organization and Personal. Personal tokens may only read meeting links where the authenticated user is the host.

        **Required scope:** `meetinglink:read`

        Parameters
        ----------
        id : str
            Meeting Link ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LinkInfoMeetingResponse
            Meeting link info

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.link_info(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        )
        """
        _response = self._raw_client.link_info(id=id, request_options=request_options)
        return _response.data

    def update_link(
        self,
        *,
        id: str,
        name: str,
        host: typing.Optional[str] = OMIT,
        start: typing.Optional[dt.datetime] = OMIT,
        end: typing.Optional[dt.datetime] = OMIT,
        require_unconfirmed_email: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Update a meeting link.

        **Access:** Organization and Personal. Personal tokens may only update meeting links where the authenticated user is the host.

        **Required scope:** `meetinglink:write`

        Parameters
        ----------
        id : str
            Meeting Link ID

        name : str
            Meeting Name

        host : typing.Optional[str]
            (Optional) Meeting Host Email.

            The Host may NOT be updated.
            As a result, this property may be omitted or empty.
            If it is provided, it MUST match the existing value.

        start : typing.Optional[dt.datetime]
            (Optional) Meeting start time in RFC3339.

        end : typing.Optional[dt.datetime]
            (Optional) Meeting end time in RFC3339.

        require_unconfirmed_email : typing.Optional[bool]
            (Optional) If true, guests must verify ownership of their email address before joining.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import datetime

        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meeting.update_link(
            id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            name="Q1 Planning Session - Updated",
            start=datetime.datetime.fromisoformat(
                "2026-02-15 15:00:00+00:00",
            ),
            end=datetime.datetime.fromisoformat(
                "2026-02-15 16:30:00+00:00",
            ),
        )
        """
        _response = self._raw_client.update_link(
            id=id,
            name=name,
            host=host,
            start=start,
            end=end,
            require_unconfirmed_email=require_unconfirmed_email,
            request_options=request_options,
        )
        return _response.data


class AsyncMeetingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMeetingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMeetingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMeetingClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        before: typing.Optional[dt.datetime] = None,
        after: typing.Optional[dt.datetime] = None,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        expand: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMeetingResponse:
        """
        List meetings, ordered newest-first.

        **Access:** Organization and Personal. Personal tokens return meetings the
        authenticated user participated in. Organization tokens return every meeting
        in the Roam only with [`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread);
        without it, results are limited to meetings the install's bot has access to.

        **Required scope:** `meetings:read` (add `admin:meetings:read` for roam-wide org access)

        Parameters
        ----------
        before : typing.Optional[dt.datetime]
            Only return meetings that started before this time (RFC-3339). Sub-millisecond precision is truncated.

        after : typing.Optional[dt.datetime]
            Only return meetings that started after this time (RFC-3339). Sub-millisecond precision is truncated.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        limit : typing.Optional[int]
            Number of meetings to return per page. Capped to **10** when
            `expand` includes `summary`, `actionItems`, or `chapters`, since
            expanded payloads are substantially larger.

        expand : typing.Optional[str]
            Comma-separated list of fields to inline on each meeting. Allowed
            values are `summary`, `actionItems`, and `chapters` — same shape
            as on [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info). Use this to
            avoid N+1 follow-up calls when scanning many recent meetings.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMeetingResponse
            Meetings retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            before=before, after=after, cursor=cursor, limit=limit, expand=expand, request_options=request_options
        )
        return _response.data

    async def info(
        self,
        *,
        id: str,
        max_participants: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InfoMeetingResponse:
        """
        Get detailed information about a specific meeting, including AI-generated summary, action items, and chapters.

        Participants are included inline up to the `maxParticipants` limit. For meetings with more participants, use [`/meeting.participants`](https://developer.ro.am/docs/api/meeting-participants) to paginate through the full list.

        **Access:** Organization and Personal. Personal tokens are limited to meetings
        the authenticated user participated in. Organization tokens without
        [`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread)
        are limited to meetings the install's bot has access to.

        **Required scope:** `meetings:read` (add `admin:meetings:read` for roam-wide org access; add `user:read` to include participants, `user:read.email` for participant emails)

        Parameters
        ----------
        id : str
            The meeting ID.

        max_participants : typing.Optional[int]
            Maximum number of participants to resolve and include inline. Use `/meeting.participants` for full pagination.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InfoMeetingResponse
            Meeting info retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.info(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.info(
            id=id, max_participants=max_participants, request_options=request_options
        )
        return _response.data

    async def participants(
        self,
        *,
        id: str,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ParticipantsMeetingResponse:
        """
        Paginate through all participants of a meeting. This is the dedicated endpoint for retrieving the full participant list, complementing the capped inline participants in [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info).

        Pagination uses an **opaque cursor** (not a row offset). Pass `nextCursor`
        from a previous response as `cursor` to fetch the next page. Invalid cursors
        return `error: "invalid_cursor"` — see [Responses and Errors](https://developer.ro.am/docs/guides/responses-and-errors).

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read` and `user:read` (add `user:read.email` for participant emails)

        Parameters
        ----------
        id : str
            The meeting ID.

        limit : typing.Optional[int]
            Number of participants to return per page (default 50, max 200).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not parse or construct cursors yourself.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ParticipantsMeetingResponse
            Participants retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.participants(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.participants(
            id=id, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def transcript(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TranscriptMeetingResponse:
        """
        Retrieve the transcript for a meeting.

        Supports content negotiation:
        - **JSON** (default): Returns structured transcript with cues containing speaker IDs, text, and timing
        - **WebVTT**: Set `Accept: text/vtt` header to receive standard WebVTT format with speaker voice tags

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read`

        **Errors** (see [Responses and Errors](https://developer.ro.am/docs/guides/responses-and-errors)):

        | `error` code | Meaning |
        |--------------|---------|
        | `meeting_not_found` | Unknown or inaccessible meeting |
        | `transcript_pending` | Not ready yet — retry later (may include `Retry-After`) |
        | `transcript_unavailable` | Meeting was not transcribed — stop retrying |
        | `upstream_timeout` | Timed out waiting on an upstream service — retry |

        Parameters
        ----------
        id : str
            The meeting ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TranscriptMeetingResponse
            Transcript retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.transcript(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.transcript(id=id, request_options=request_options)
        return _response.data

    async def search(
        self,
        *,
        query: str,
        after: typing.Optional[dt.date] = None,
        before: typing.Optional[dt.date] = None,
        timezone: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchMeetingResponse:
        """
        AI-powered search across meeting transcripts and summaries.

        **Access:** Personal access only. Organization (account-level) tokens are not supported.

        **Required scope:** `meetings:read`

        Parameters
        ----------
        query : str
            Search query string.

        after : typing.Optional[dt.date]
            Only return results from meetings after this date (YYYY-MM-DD).

        before : typing.Optional[dt.date]
            Only return results from meetings before this date (YYYY-MM-DD).

        timezone : typing.Optional[str]
            Timezone for date interpretation (e.g. "America/New_York").

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchMeetingResponse
            Search results retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.search(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            query=query, after=after, before=before, timezone=timezone, request_options=request_options
        )
        return _response.data

    async def prompt(
        self, *, id: str, prompt: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PromptMeetingResponse:
        """
        Ask an AI question about a meeting's transcript content. Returns a natural language response based on the meeting transcript.

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read`

        Parameters
        ----------
        id : str
            The meeting ID.

        prompt : str
            The question to ask about the meeting.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PromptMeetingResponse
            Response generated successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.prompt(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                prompt="What action items were assigned to Alex?",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.prompt(id=id, prompt=prompt, request_options=request_options)
        return _response.data

    async def share_link(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ShareLinkMeetingResponse:
        """
        Returns a shareable URL for a meeting that you can distribute to others. Pass the `id` of a meeting obtained from [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) or [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info).

        This endpoint is **get-or-create**: it returns the meeting's existing share link, or mints one the first time it is called for that meeting. Repeat calls for the same meeting return the same URL.

        Creating a share link is a deliberate action, which is why it has its own endpoint rather than being returned as a field on `meeting.list` / `meeting.info` — fetching a meeting never mints a shareable link as a side effect. You can only create a share link for a meeting you can access; the same access check as `meeting.info` applies.

        **Access:** Organization and Personal. Personal access tokens restrict to meetings the authenticated user participated in.

        **Required scope:** `meetings:read`

        Parameters
        ----------
        id : str
            The meeting ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShareLinkMeetingResponse
            The meeting's shareable link.

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.share_link(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.share_link(id=id, request_options=request_options)
        return _response.data

    async def create_link(
        self,
        *,
        name: str,
        host: typing.Optional[str] = OMIT,
        start: typing.Optional[dt.datetime] = OMIT,
        end: typing.Optional[dt.datetime] = OMIT,
        require_unconfirmed_email: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateLinkMeetingResponse:
        """
        Create a meeting link.

        **Access:** Organization and Personal. In Organization mode, specify the host by email. In Personal mode, the host defaults to the authenticated user.

        **Required scope:** `meeting:write` or `meetinglink:write`

        Parameters
        ----------
        name : str
            Meeting Name

        host : typing.Optional[str]
            Meeting Host Email, matching a member of your Roam.

            Required for Organization tokens. For Personal tokens, this is optional and defaults to the authenticated user. If provided with a Personal token, it must match the authenticated user's email.

        start : typing.Optional[dt.datetime]
            (Optional) Meeting start time in RFC3339.

        end : typing.Optional[dt.datetime]
            (Optional) Meeting end time in RFC3339.

        require_unconfirmed_email : typing.Optional[bool]
            (Optional) If true, guests must verify ownership of their email address before joining.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateLinkMeetingResponse
            Meeting link successfully created

        Examples
        --------
        import asyncio
        import datetime

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.create_link(
                name="Q1 Planning Session",
                host="alex.chen@example.com",
                start=datetime.datetime.fromisoformat(
                    "2026-02-15 14:00:00+00:00",
                ),
                end=datetime.datetime.fromisoformat(
                    "2026-02-15 15:00:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_link(
            name=name,
            host=host,
            start=start,
            end=end,
            require_unconfirmed_email=require_unconfirmed_email,
            request_options=request_options,
        )
        return _response.data

    async def link_info(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> LinkInfoMeetingResponse:
        """
        Get a meeting link.

        **Access:** Organization and Personal. Personal tokens may only read meeting links where the authenticated user is the host.

        **Required scope:** `meetinglink:read`

        Parameters
        ----------
        id : str
            Meeting Link ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LinkInfoMeetingResponse
            Meeting link info

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.link_info(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.link_info(id=id, request_options=request_options)
        return _response.data

    async def update_link(
        self,
        *,
        id: str,
        name: str,
        host: typing.Optional[str] = OMIT,
        start: typing.Optional[dt.datetime] = OMIT,
        end: typing.Optional[dt.datetime] = OMIT,
        require_unconfirmed_email: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Update a meeting link.

        **Access:** Organization and Personal. Personal tokens may only update meeting links where the authenticated user is the host.

        **Required scope:** `meetinglink:write`

        Parameters
        ----------
        id : str
            Meeting Link ID

        name : str
            Meeting Name

        host : typing.Optional[str]
            (Optional) Meeting Host Email.

            The Host may NOT be updated.
            As a result, this property may be omitted or empty.
            If it is provided, it MUST match the existing value.

        start : typing.Optional[dt.datetime]
            (Optional) Meeting start time in RFC3339.

        end : typing.Optional[dt.datetime]
            (Optional) Meeting end time in RFC3339.

        require_unconfirmed_email : typing.Optional[bool]
            (Optional) If true, guests must verify ownership of their email address before joining.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio
        import datetime

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meeting.update_link(
                id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name="Q1 Planning Session - Updated",
                start=datetime.datetime.fromisoformat(
                    "2026-02-15 15:00:00+00:00",
                ),
                end=datetime.datetime.fromisoformat(
                    "2026-02-15 16:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_link(
            id=id,
            name=name,
            host=host,
            start=start,
            end=end,
            require_unconfirmed_email=require_unconfirmed_email,
            request_options=request_options,
        )
        return _response.data
