# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawReactionClient, RawReactionClient
from .types.list_reaction_response import ListReactionResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ReactionClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawReactionClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawReactionClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawReactionClient
        """
        return self._raw_client

    def add(
        self,
        *,
        chat_id: str,
        timestamp: int,
        name: str,
        thread_timestamp: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Add a reaction to a message in a chat.

        To react to a thread reply, provide the `threadTimestamp` of the parent message
        and the `timestamp` of the specific reply.

        **Access:** The organization bot or personal-token **owner** must be a
        member of the chat (`403` `not_in_chat` otherwise).

        **Required scope:** `chat:send_message` or `chat:write`

        Parameters
        ----------
        chat_id : str
            The chat containing the message to react to.

        timestamp : int
            Timestamp of the message to react to (Unix microseconds).

        name : str
            Name of the reaction to add (e.g. "thumbs_up", "heart", "100").

        thread_timestamp : typing.Optional[int]
            Timestamp of the parent thread message (Unix microseconds), if reacting to a thread reply.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.reaction.add(
            chat_id="7be17589-4b9a-4524-bddb-ce60abea08e6",
            timestamp=1755723832718034,
            name="thumbs_up",
        )
        """
        _response = self._raw_client.add(
            chat_id=chat_id,
            timestamp=timestamp,
            name=name,
            thread_timestamp=thread_timestamp,
            request_options=request_options,
        )
        return _response.data

    def remove(
        self,
        *,
        chat_id: str,
        timestamp: int,
        name: str,
        thread_timestamp: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Remove a reaction from a message in a chat.

        Only reactions added by the authenticated app can be removed.

        To remove a reaction from a thread reply, provide the `threadTimestamp` of the parent message
        and the `timestamp` of the specific reply.

        **Required scope:** `chat:send_message` or `chat:write`

        Parameters
        ----------
        chat_id : str
            The chat containing the message.

        timestamp : int
            Timestamp of the message (Unix microseconds).

        name : str
            Name of the reaction to remove (e.g. "thumbs_up", "heart").

        thread_timestamp : typing.Optional[int]
            Timestamp of the parent thread message (Unix microseconds), if removing from a thread reply.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.reaction.remove(
            chat_id="7be17589-4b9a-4524-bddb-ce60abea08e6",
            timestamp=1755723832718034,
            name="thumbs_up",
        )
        """
        _response = self._raw_client.remove(
            chat_id=chat_id,
            timestamp=timestamp,
            name=name,
            thread_timestamp=thread_timestamp,
            request_options=request_options,
        )
        return _response.data

    def list(
        self,
        *,
        chat_id: str,
        timestamp: int,
        thread_timestamp: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListReactionResponse:
        """
        List reactions on a specific message, grouped by emoji (Slack-style
        `{name, count, users}`). Poll votes are returned separately in `pollVotes`
        rather than folded into `reactions`.

        `users` contains visible principal IDs only. Unknown or unauthorized actors
        are omitted, and `count` is recomputed from the returned IDs. Hydrate them
        with `user.list?ids`; these arrays do not carry inline type fields.

        To list reactions on a thread reply, provide the `threadTimestamp` of the
        parent message and the `timestamp` of the specific reply.

        **Required scope:** `chat:history`

        Parameters
        ----------
        chat_id : str
            The chat containing the message.

        timestamp : int
            Timestamp of the message (Unix microseconds).

        thread_timestamp : typing.Optional[int]
            Timestamp of the parent thread message (Unix microseconds), if listing reactions on a thread reply.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListReactionResponse
            Reactions retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.reaction.list(
            chat_id="chatId",
            timestamp=1,
        )
        """
        _response = self._raw_client.list(
            chat_id=chat_id, timestamp=timestamp, thread_timestamp=thread_timestamp, request_options=request_options
        )
        return _response.data


class AsyncReactionClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawReactionClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawReactionClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawReactionClient
        """
        return self._raw_client

    async def add(
        self,
        *,
        chat_id: str,
        timestamp: int,
        name: str,
        thread_timestamp: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Add a reaction to a message in a chat.

        To react to a thread reply, provide the `threadTimestamp` of the parent message
        and the `timestamp` of the specific reply.

        **Access:** The organization bot or personal-token **owner** must be a
        member of the chat (`403` `not_in_chat` otherwise).

        **Required scope:** `chat:send_message` or `chat:write`

        Parameters
        ----------
        chat_id : str
            The chat containing the message to react to.

        timestamp : int
            Timestamp of the message to react to (Unix microseconds).

        name : str
            Name of the reaction to add (e.g. "thumbs_up", "heart", "100").

        thread_timestamp : typing.Optional[int]
            Timestamp of the parent thread message (Unix microseconds), if reacting to a thread reply.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reaction.add(
                chat_id="7be17589-4b9a-4524-bddb-ce60abea08e6",
                timestamp=1755723832718034,
                name="thumbs_up",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add(
            chat_id=chat_id,
            timestamp=timestamp,
            name=name,
            thread_timestamp=thread_timestamp,
            request_options=request_options,
        )
        return _response.data

    async def remove(
        self,
        *,
        chat_id: str,
        timestamp: int,
        name: str,
        thread_timestamp: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Remove a reaction from a message in a chat.

        Only reactions added by the authenticated app can be removed.

        To remove a reaction from a thread reply, provide the `threadTimestamp` of the parent message
        and the `timestamp` of the specific reply.

        **Required scope:** `chat:send_message` or `chat:write`

        Parameters
        ----------
        chat_id : str
            The chat containing the message.

        timestamp : int
            Timestamp of the message (Unix microseconds).

        name : str
            Name of the reaction to remove (e.g. "thumbs_up", "heart").

        thread_timestamp : typing.Optional[int]
            Timestamp of the parent thread message (Unix microseconds), if removing from a thread reply.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reaction.remove(
                chat_id="7be17589-4b9a-4524-bddb-ce60abea08e6",
                timestamp=1755723832718034,
                name="thumbs_up",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove(
            chat_id=chat_id,
            timestamp=timestamp,
            name=name,
            thread_timestamp=thread_timestamp,
            request_options=request_options,
        )
        return _response.data

    async def list(
        self,
        *,
        chat_id: str,
        timestamp: int,
        thread_timestamp: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListReactionResponse:
        """
        List reactions on a specific message, grouped by emoji (Slack-style
        `{name, count, users}`). Poll votes are returned separately in `pollVotes`
        rather than folded into `reactions`.

        `users` contains visible principal IDs only. Unknown or unauthorized actors
        are omitted, and `count` is recomputed from the returned IDs. Hydrate them
        with `user.list?ids`; these arrays do not carry inline type fields.

        To list reactions on a thread reply, provide the `threadTimestamp` of the
        parent message and the `timestamp` of the specific reply.

        **Required scope:** `chat:history`

        Parameters
        ----------
        chat_id : str
            The chat containing the message.

        timestamp : int
            Timestamp of the message (Unix microseconds).

        thread_timestamp : typing.Optional[int]
            Timestamp of the parent thread message (Unix microseconds), if listing reactions on a thread reply.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListReactionResponse
            Reactions retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.reaction.list(
                chat_id="chatId",
                timestamp=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            chat_id=chat_id, timestamp=timestamp, thread_timestamp=thread_timestamp, request_options=request_options
        )
        return _response.data
