# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from __future__ import annotations

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .add_group_request_members_item import AddGroupRequestMembersItem
    from .add_group_request_members_item_role import AddGroupRequestMembersItemRole
    from .create_group_request_members_item import CreateGroupRequestMembersItem
    from .create_group_request_members_item_role import CreateGroupRequestMembersItemRole
    from .list_group_response import ListGroupResponse
    from .list_group_response_groups_item import ListGroupResponseGroupsItem
    from .list_group_response_groups_item_access_mode import ListGroupResponseGroupsItemAccessMode
    from .list_group_response_groups_item_type import ListGroupResponseGroupsItemType
    from .members_group_response import MembersGroupResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AddGroupRequestMembersItem": ".add_group_request_members_item",
    "AddGroupRequestMembersItemRole": ".add_group_request_members_item_role",
    "CreateGroupRequestMembersItem": ".create_group_request_members_item",
    "CreateGroupRequestMembersItemRole": ".create_group_request_members_item_role",
    "ListGroupResponse": ".list_group_response",
    "ListGroupResponseGroupsItem": ".list_group_response_groups_item",
    "ListGroupResponseGroupsItemAccessMode": ".list_group_response_groups_item_access_mode",
    "ListGroupResponseGroupsItemType": ".list_group_response_groups_item_type",
    "MembersGroupResponse": ".members_group_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddGroupRequestMembersItem",
    "AddGroupRequestMembersItemRole",
    "CreateGroupRequestMembersItem",
    "CreateGroupRequestMembersItemRole",
    "ListGroupResponse",
    "ListGroupResponseGroupsItem",
    "ListGroupResponseGroupsItemAccessMode",
    "ListGroupResponseGroupsItemType",
    "MembersGroupResponse",
]
