# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class InfoTokenResponseUser(UniversalBaseModel):
    """
    The authenticated user or bot
    """

    id: str = pydantic.Field()
    """
    User/bot ID
    """

    name: str = pydantic.Field()
    """
    Display name
    """

    image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageUrl"),
        pydantic.Field(alias="imageUrl", description="Profile image URL"),
    ] = None
    """
    Profile image URL
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address. Included for personal access tokens with the `user:read.email` scope.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
