# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .info_token_response_bot import InfoTokenResponseBot
from .info_token_response_roam import InfoTokenResponseRoam
from .info_token_response_user import InfoTokenResponseUser


class InfoTokenResponse(UniversalBaseModel):
    user: InfoTokenResponseUser = pydantic.Field()
    """
    The authenticated user or bot
    """

    bot: typing.Optional[InfoTokenResponseBot] = pydantic.Field(default=None)
    """
    The bot persona associated with the token. Present only for personal
    access tokens, where `user` is the authenticated person and `bot` is
    the persona that messages are posted as. Omitted for organization
    tokens, where `user` is the app's own identity.
    """

    client_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="clientId"),
        pydantic.Field(alias="clientId", description="The API client (app) ID this token belongs to."),
    ]
    """
    The API client (app) ID this token belongs to.
    """

    scopes: typing.List[str] = pydantic.Field()
    """
    List of OAuth scopes granted to this token
    """

    roam: InfoTokenResponseRoam = pydantic.Field()
    """
    Information about the Roam workspace
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
