# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class InfoTokenResponseBot(UniversalBaseModel):
    """
    The bot persona associated with the token. Present only for personal
    access tokens, where `user` is the authenticated person and `bot` is
    the persona that messages are posted as. Omitted for organization
    tokens, where `user` is the app's own identity.
    """

    id: str = pydantic.Field()
    """
    Bot ID
    """

    name: str = pydantic.Field()
    """
    Bot display name
    """

    image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageUrl"),
        pydantic.Field(alias="imageUrl", description="Bot profile image URL"),
    ] = None
    """
    Bot profile image URL
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
