# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawMeetingsClient, RawMeetingsClient
from .types.recording_list_response import RecordingListResponse


class MeetingsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMeetingsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMeetingsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMeetingsClient
        """
        return self._raw_client

    def recording_list(
        self,
        *,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordingListResponse:
        """
        **Legacy:** Prefer [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) /
        [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info) for new integrations.

        Lists recordings in your home Roam, filtered by date range (after/before).
        Organization clients without roam-wide meeting access
        ([`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread))
        receive `403`; use [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) instead.
        This route remains registered for existing callers. It returns v0-style
        identifiers and is not a v1 media-download path.

        The plural alias `/recordings.list` is also registered for existing callers;
        use this singular form in new documentation and tooling.

        The ordering of results depends on the filter specified:

        - When no parameters are provided, the most recent recordings are returned,
          sorted in reverse chronological order. This is equivalent to specifying `before`
          as NOW and leaving `after` unspecified.

        - If `after` is specified, the results are sorted in forward chronological order.

        Either dates or datetimes may be specified. Dates are interpreted in UTC.

        **Access:** Organization only. Requires roam-wide meeting access.

        **Required scope:** `recordings:read` and `admin:meetings:read` (or a grandfathered roam-wide API key)

        Parameters
        ----------
        after : typing.Optional[str]
            The datetime to begin listing recordings (YYYY-MM-DD or RFC-3339).
            Defaults to "no filter".

        before : typing.Optional[str]
            The datetime until which to list recordings (YYYY-MM-DD or RFC-3339).
            Defaults to "now".

        limit : typing.Optional[int]
            The number of recordings to return per response. Default is 10.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordingListResponse
            OK

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.meetings.recording_list()
        """
        _response = self._raw_client.recording_list(
            after=after, before=before, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data


class AsyncMeetingsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMeetingsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMeetingsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMeetingsClient
        """
        return self._raw_client

    async def recording_list(
        self,
        *,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordingListResponse:
        """
        **Legacy:** Prefer [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) /
        [`/meeting.info`](https://developer.ro.am/docs/api/meeting-info) for new integrations.

        Lists recordings in your home Roam, filtered by date range (after/before).
        Organization clients without roam-wide meeting access
        ([`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread))
        receive `403`; use [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) instead.
        This route remains registered for existing callers. It returns v0-style
        identifiers and is not a v1 media-download path.

        The plural alias `/recordings.list` is also registered for existing callers;
        use this singular form in new documentation and tooling.

        The ordering of results depends on the filter specified:

        - When no parameters are provided, the most recent recordings are returned,
          sorted in reverse chronological order. This is equivalent to specifying `before`
          as NOW and leaving `after` unspecified.

        - If `after` is specified, the results are sorted in forward chronological order.

        Either dates or datetimes may be specified. Dates are interpreted in UTC.

        **Access:** Organization only. Requires roam-wide meeting access.

        **Required scope:** `recordings:read` and `admin:meetings:read` (or a grandfathered roam-wide API key)

        Parameters
        ----------
        after : typing.Optional[str]
            The datetime to begin listing recordings (YYYY-MM-DD or RFC-3339).
            Defaults to "no filter".

        before : typing.Optional[str]
            The datetime until which to list recordings (YYYY-MM-DD or RFC-3339).
            Defaults to "now".

        limit : typing.Optional[int]
            The number of recordings to return per response. Default is 10.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordingListResponse
            OK

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.meetings.recording_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.recording_list(
            after=after, before=before, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data
