# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.user import User
from .raw_client import AsyncRawUserClient, RawUserClient
from .types.list_user_response import ListUserResponse


class UserClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUserClient
        """
        return self._raw_client

    def list(
        self,
        *,
        ids: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        expand: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserResponse:
        """
        List workspace members, or hydrate an explicit ordered set of principal IDs.

        Without `ids`, this is the active workspace member directory: guests,
        bots, and archived/deactivated members are never enumerated. Members are
        returned in the order they were added to the account.

        With `ids`, the endpoint becomes an unpaginated principal hydrator. Pass one
        comma-separated value containing at most 100 bare or tagged IDs. Duplicate
        tokens are deduplicated in first-seen order; resolved entries are returned
        in that order. Unknown IDs, groups, and unauthorized principals are silently
        omitted. Explicit lookup may resolve archived/deactivated users and
        authorized automated actors. The response keeps the existing `users` key
        but its entries are principals, and `nextCursor` is omitted.

        `ids` cannot be combined with `q`, `limit`, or `cursor`. `expand=status`
        remains supported in either mode.

        See [Identity & Principals](https://developer.ro.am/docs/guides/identity-and-principals).

        **Required scope:** `user:read` (add `user:read.email` to include email addresses, `user:read.status` to expand presence status and `willReturn`)

        **Access:** Organization and Personal.

        Parameters
        ----------
        ids : typing.Optional[str]
            One comma-separated list of up to 100 bare or tagged principal IDs.
            Repeating the `ids` query parameter, including empty tokens, or combining
            it with `q`, `limit`, or `cursor` returns `invalid_parameter`.

        q : typing.Optional[str]
            Case-insensitive member-directory filter by name. Also matches email
            when the token has `user:read.email`. Cannot be combined with `ids`.

        limit : typing.Optional[int]
            The number of directory members to return per response. Default is 10. Cannot be combined with `ids`.

        cursor : typing.Optional[str]
            Opaque directory cursor from a previous response's `nextCursor`. Cannot be combined with `ids`.

        expand : typing.Optional[str]
            Comma-separated list of additional fields. Supported: `status` (requires `user:read.status`). Expanding `status` also returns `willReturn` when set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserResponse
            Directory members or explicitly hydrated principals retrieved successfully.

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.user.list()
        """
        _response = self._raw_client.list(
            ids=ids, q=q, limit=limit, cursor=cursor, expand=expand, request_options=request_options
        )
        return _response.data

    def info(
        self,
        *,
        id: typing.Optional[str] = None,
        email: typing.Optional[str] = None,
        expand: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> User:
        """
        Resolve a v1 principal by ID, or look up a workspace member by email.

        ID lookup resolves active or archived members, guests, and authorized
        automated actors (classic bots, agents, assistants, and coworkers). The
        response always includes `type: "user" | "bot"`; guests additionally have
        `isGuest: true`. Groups, unknown IDs, and automated actors outside the
        caller's Roam/account/owner boundary return `user_not_found`.

        Email lookup remains workspace-member-only. Personal access tokens and the
        MCP `user_info` tool may use ID lookup.

        Provide either `id` or `email`, not both.

        See [Identity & Principals](https://developer.ro.am/docs/guides/identity-and-principals) for the
        taxonomy, visibility rules, and directory-versus-hydration guidance.

        **Required scope:** `user:read` (add `user:read.email` to look up by email or include email in response, `user:read.status` to expand presence status, availability, and `willReturn`)

        **Access:** Organization and Personal.

        Parameters
        ----------
        id : typing.Optional[str]
            A bare or tagged principal ID. Mutually exclusive with `email`.

        email : typing.Optional[str]
            The user's email address. Mutually exclusive with `id`. Requires `user:read.email` scope.

        expand : typing.Optional[str]
            Comma-separated list of additional fields to include. Supported: `status`, `available` (each requires `user:read.status`). Expanding `status` also returns `willReturn` when the user has a future out-of-office entry.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            Principal info retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.user.info()
        """
        _response = self._raw_client.info(id=id, email=email, expand=expand, request_options=request_options)
        return _response.data


class AsyncUserClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUserClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        ids: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        expand: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListUserResponse:
        """
        List workspace members, or hydrate an explicit ordered set of principal IDs.

        Without `ids`, this is the active workspace member directory: guests,
        bots, and archived/deactivated members are never enumerated. Members are
        returned in the order they were added to the account.

        With `ids`, the endpoint becomes an unpaginated principal hydrator. Pass one
        comma-separated value containing at most 100 bare or tagged IDs. Duplicate
        tokens are deduplicated in first-seen order; resolved entries are returned
        in that order. Unknown IDs, groups, and unauthorized principals are silently
        omitted. Explicit lookup may resolve archived/deactivated users and
        authorized automated actors. The response keeps the existing `users` key
        but its entries are principals, and `nextCursor` is omitted.

        `ids` cannot be combined with `q`, `limit`, or `cursor`. `expand=status`
        remains supported in either mode.

        See [Identity & Principals](https://developer.ro.am/docs/guides/identity-and-principals).

        **Required scope:** `user:read` (add `user:read.email` to include email addresses, `user:read.status` to expand presence status and `willReturn`)

        **Access:** Organization and Personal.

        Parameters
        ----------
        ids : typing.Optional[str]
            One comma-separated list of up to 100 bare or tagged principal IDs.
            Repeating the `ids` query parameter, including empty tokens, or combining
            it with `q`, `limit`, or `cursor` returns `invalid_parameter`.

        q : typing.Optional[str]
            Case-insensitive member-directory filter by name. Also matches email
            when the token has `user:read.email`. Cannot be combined with `ids`.

        limit : typing.Optional[int]
            The number of directory members to return per response. Default is 10. Cannot be combined with `ids`.

        cursor : typing.Optional[str]
            Opaque directory cursor from a previous response's `nextCursor`. Cannot be combined with `ids`.

        expand : typing.Optional[str]
            Comma-separated list of additional fields. Supported: `status` (requires `user:read.status`). Expanding `status` also returns `willReturn` when set.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListUserResponse
            Directory members or explicitly hydrated principals retrieved successfully.

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.user.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            ids=ids, q=q, limit=limit, cursor=cursor, expand=expand, request_options=request_options
        )
        return _response.data

    async def info(
        self,
        *,
        id: typing.Optional[str] = None,
        email: typing.Optional[str] = None,
        expand: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> User:
        """
        Resolve a v1 principal by ID, or look up a workspace member by email.

        ID lookup resolves active or archived members, guests, and authorized
        automated actors (classic bots, agents, assistants, and coworkers). The
        response always includes `type: "user" | "bot"`; guests additionally have
        `isGuest: true`. Groups, unknown IDs, and automated actors outside the
        caller's Roam/account/owner boundary return `user_not_found`.

        Email lookup remains workspace-member-only. Personal access tokens and the
        MCP `user_info` tool may use ID lookup.

        Provide either `id` or `email`, not both.

        See [Identity & Principals](https://developer.ro.am/docs/guides/identity-and-principals) for the
        taxonomy, visibility rules, and directory-versus-hydration guidance.

        **Required scope:** `user:read` (add `user:read.email` to look up by email or include email in response, `user:read.status` to expand presence status, availability, and `willReturn`)

        **Access:** Organization and Personal.

        Parameters
        ----------
        id : typing.Optional[str]
            A bare or tagged principal ID. Mutually exclusive with `email`.

        email : typing.Optional[str]
            The user's email address. Mutually exclusive with `id`. Requires `user:read.email` scope.

        expand : typing.Optional[str]
            Comma-separated list of additional fields to include. Supported: `status`, `available` (each requires `user:read.status`). Expanding `status` also returns `willReturn` when the user has a future out-of-office entry.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        User
            Principal info retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.user.info()


        asyncio.run(main())
        """
        _response = await self._raw_client.info(id=id, email=email, expand=expand, request_options=request_options)
        return _response.data
