# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.method_not_allowed_error import MethodNotAllowedError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error import Error
from .types.create_event_calendar_response import CreateEventCalendarResponse
from .types.list_calendar_response import ListCalendarResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCalendarClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_event(
        self,
        *,
        title: str,
        start: dt.datetime,
        end: dt.datetime,
        description: typing.Optional[str] = OMIT,
        all_day: typing.Optional[bool] = OMIT,
        rrule: typing.Optional[str] = OMIT,
        time_zone: typing.Optional[str] = OMIT,
        attendees: typing.Optional[typing.Sequence[str]] = OMIT,
        host: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateEventCalendarResponse]:
        """
        Create a calendar event on the host's connected calendar. A Roam meeting link
        is automatically attached and email notifications are sent to attendees.

        The event is written to the first active, writable calendar associated with the
        host. The host must have a connected calendar provider (e.g. Google, Microsoft).

        **Recurring events:** Provide `rrule` to create a recurring series. A
        `timeZone` is required for recurring events.

        **All-day events:** Set `allDay: true`; `start` and `end` are interpreted as
        dates and normalized to UTC midnight.

        **Access:** Organization and Personal. For Organization tokens, the `host` email
        is required and identifies the calendar owner. For Personal tokens, `host`
        defaults to the authenticated user; if provided it must match the
        authenticated user's email.

        **Required scope:** `calendar:write`

        Parameters
        ----------
        title : str
            Event title.

        start : dt.datetime
            Event start time (RFC3339). For all-day events, the date portion is used.

        end : dt.datetime
            Event end time (RFC3339). For all-day events, the date portion is used.

        description : typing.Optional[str]
            (Optional) Event description.

        all_day : typing.Optional[bool]
            Whether this is an all-day event. Defaults to false.

        rrule : typing.Optional[str]
            (Optional) iCalendar RFC 5545 recurrence rule, e.g. `FREQ=WEEKLY;COUNT=10`.
            When provided, `timeZone` is required.

        time_zone : typing.Optional[str]
            IANA timezone name, e.g. `America/New_York`. Required for recurring
            events; recommended for all events. Defaults to `UTC` when omitted.

        attendees : typing.Optional[typing.Sequence[str]]
            Attendee email addresses. Each entry may be a plain email
            (`user@example.com`) or an address string (`Name <user@example.com>`).

        host : typing.Optional[str]
            Calendar host email. Required for Organization tokens. For Personal
            tokens, defaults to the authenticated user and, if provided, must
            match the authenticated user's email.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateEventCalendarResponse]
            Calendar event created successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            "calendar.event.create",
            method="POST",
            json={
                "title": title,
                "description": description,
                "start": start,
                "end": end,
                "allDay": all_day,
                "rrule": rrule,
                "timeZone": time_zone,
                "attendees": attendees,
                "host": host,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateEventCalendarResponse,
                    parse_obj_as(
                        type_=CreateEventCalendarResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list(
        self,
        *,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListCalendarResponse]:
        """
        List events from the authenticated user's connected calendars within
        a date range.

        Pulls events from every active personal calendar attached to the user
        (e.g. Google, Microsoft) and merges them into a single chronological
        list. Canceled events are omitted.

        **Date range:** Defaults to a 7-day window starting today (caller's
        timezone). Pass `startDate` to shift the window's start; pass
        `endDate` to set its end (inclusive). Both are interpreted as
        `YYYY-MM-DD` in the caller's timezone.

        **Access:** Personal access only. Organization tokens do not have
        access to individual calendars and receive a `400`.

        **Required scope:** `calendar:read`

        `meetings:read` also grants this endpoint, but only for API clients
        registered **before 2026-07-29T00:00Z**. Clients registered on or after that
        date must hold `calendar:read`, or the call fails with `403` /
        `missing_scope`. See [Scopes](https://developer.ro.am/docs/guides/scopes).

        Parameters
        ----------
        start_date : typing.Optional[str]
            First day to include (`YYYY-MM-DD`, caller's timezone). Defaults to today.

        end_date : typing.Optional[str]
            Last day to include (`YYYY-MM-DD`, caller's timezone, inclusive).
            Defaults to seven days after the resolved `startDate`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListCalendarResponse]
            Calendar events retrieved successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            "calendar.list",
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListCalendarResponse,
                    parse_obj_as(
                        type_=ListCalendarResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCalendarClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_event(
        self,
        *,
        title: str,
        start: dt.datetime,
        end: dt.datetime,
        description: typing.Optional[str] = OMIT,
        all_day: typing.Optional[bool] = OMIT,
        rrule: typing.Optional[str] = OMIT,
        time_zone: typing.Optional[str] = OMIT,
        attendees: typing.Optional[typing.Sequence[str]] = OMIT,
        host: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateEventCalendarResponse]:
        """
        Create a calendar event on the host's connected calendar. A Roam meeting link
        is automatically attached and email notifications are sent to attendees.

        The event is written to the first active, writable calendar associated with the
        host. The host must have a connected calendar provider (e.g. Google, Microsoft).

        **Recurring events:** Provide `rrule` to create a recurring series. A
        `timeZone` is required for recurring events.

        **All-day events:** Set `allDay: true`; `start` and `end` are interpreted as
        dates and normalized to UTC midnight.

        **Access:** Organization and Personal. For Organization tokens, the `host` email
        is required and identifies the calendar owner. For Personal tokens, `host`
        defaults to the authenticated user; if provided it must match the
        authenticated user's email.

        **Required scope:** `calendar:write`

        Parameters
        ----------
        title : str
            Event title.

        start : dt.datetime
            Event start time (RFC3339). For all-day events, the date portion is used.

        end : dt.datetime
            Event end time (RFC3339). For all-day events, the date portion is used.

        description : typing.Optional[str]
            (Optional) Event description.

        all_day : typing.Optional[bool]
            Whether this is an all-day event. Defaults to false.

        rrule : typing.Optional[str]
            (Optional) iCalendar RFC 5545 recurrence rule, e.g. `FREQ=WEEKLY;COUNT=10`.
            When provided, `timeZone` is required.

        time_zone : typing.Optional[str]
            IANA timezone name, e.g. `America/New_York`. Required for recurring
            events; recommended for all events. Defaults to `UTC` when omitted.

        attendees : typing.Optional[typing.Sequence[str]]
            Attendee email addresses. Each entry may be a plain email
            (`user@example.com`) or an address string (`Name <user@example.com>`).

        host : typing.Optional[str]
            Calendar host email. Required for Organization tokens. For Personal
            tokens, defaults to the authenticated user and, if provided, must
            match the authenticated user's email.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateEventCalendarResponse]
            Calendar event created successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "calendar.event.create",
            method="POST",
            json={
                "title": title,
                "description": description,
                "start": start,
                "end": end,
                "allDay": all_day,
                "rrule": rrule,
                "timeZone": time_zone,
                "attendees": attendees,
                "host": host,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateEventCalendarResponse,
                    parse_obj_as(
                        type_=CreateEventCalendarResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list(
        self,
        *,
        start_date: typing.Optional[str] = None,
        end_date: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListCalendarResponse]:
        """
        List events from the authenticated user's connected calendars within
        a date range.

        Pulls events from every active personal calendar attached to the user
        (e.g. Google, Microsoft) and merges them into a single chronological
        list. Canceled events are omitted.

        **Date range:** Defaults to a 7-day window starting today (caller's
        timezone). Pass `startDate` to shift the window's start; pass
        `endDate` to set its end (inclusive). Both are interpreted as
        `YYYY-MM-DD` in the caller's timezone.

        **Access:** Personal access only. Organization tokens do not have
        access to individual calendars and receive a `400`.

        **Required scope:** `calendar:read`

        `meetings:read` also grants this endpoint, but only for API clients
        registered **before 2026-07-29T00:00Z**. Clients registered on or after that
        date must hold `calendar:read`, or the call fails with `403` /
        `missing_scope`. See [Scopes](https://developer.ro.am/docs/guides/scopes).

        Parameters
        ----------
        start_date : typing.Optional[str]
            First day to include (`YYYY-MM-DD`, caller's timezone). Defaults to today.

        end_date : typing.Optional[str]
            Last day to include (`YYYY-MM-DD`, caller's timezone, inclusive).
            Defaults to seven days after the resolved `startDate`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListCalendarResponse]
            Calendar events retrieved successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "calendar.list",
            method="GET",
            params={
                "startDate": start_date,
                "endDate": end_date,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListCalendarResponse,
                    parse_obj_as(
                        type_=ListCalendarResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
