# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CreateAssetResponse(UniversalBaseModel):
    asset_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="assetId"),
        pydantic.Field(
            alias="assetId",
            description="ID of the created asset. Pass it to chat.post / chat.update\nvia `assetIds`, or to story.post, once the upload completes.",
        ),
    ]
    """
    ID of the created asset. Pass it to chat.post / chat.update
    via `assetIds`, or to story.post, once the upload completes.
    """

    upload_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="uploadUrl"),
        pydantic.Field(alias="uploadUrl", description="URL to upload the file bytes to."),
    ]
    """
    URL to upload the file bytes to.
    """

    upload_method: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="uploadMethod"),
        pydantic.Field(alias="uploadMethod", description="HTTP method to use for the upload request (always `POST`)."),
    ]
    """
    HTTP method to use for the upload request (always `POST`).
    """

    upload_headers: typing_extensions.Annotated[
        typing.Dict[str, str],
        FieldMetadata(alias="uploadHeaders"),
        pydantic.Field(
            alias="uploadHeaders",
            description="Headers to send verbatim on the upload request. They authorize\nthe upload and select the single-request upload protocol.",
        ),
    ]
    """
    Headers to send verbatim on the upload request. They authorize
    the upload and select the single-request upload protocol.
    """

    image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageUrl"),
        pydantic.Field(
            alias="imageUrl",
            description='Present for `purpose: "avatar"`. Canonical public URL to pass\nas `sender.imageUrl` or On-Air `hosts[].imageUrl` after the\nupload completes. 404s until image processing finishes.',
        ),
    ] = None
    """
    Present for `purpose: "avatar"`. Canonical public URL to pass
    as `sender.imageUrl` or On-Air `hosts[].imageUrl` after the
    upload completes. 404s until image processing finishes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
