# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

CreateAssetRequestPurpose = typing.Union[typing.Literal["file", "story", "avatar"], typing.Any]
