# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawConversationClient, RawConversationClient
from .types.list_conversation_response import ListConversationResponse


class ConversationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConversationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConversationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConversationClient
        """
        return self._raw_client

    def list(
        self,
        *,
        before: typing.Optional[dt.datetime] = None,
        after: typing.Optional[dt.datetime] = None,
        ascending: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConversationResponse:
        """
        Lists conversations (meetings) that occurred in your Roam, with participant details.

        **Access:**
        - **Organization with [`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread)**
          (or a grandfathered roam-wide API key): all conversations in the workspace.
        - **Personal access tokens:** supported — returns only conversations the
          token owner participated in (matched by confirmed email).
        - **Organization without roam-wide meeting access** must use
          [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) instead (`403`).

        **Required scope:** `meetings:read` (add `admin:meetings:read` for roam-wide org access)

        Participant details require `user:read` scope. Email addresses require `user:read.email` scope.

        Parameters
        ----------
        before : typing.Optional[dt.datetime]
            Only return conversations that started before this ISO-8601 timestamp.

        after : typing.Optional[dt.datetime]
            Only return conversations that started after this ISO-8601 timestamp.

        ascending : typing.Optional[bool]
            Sort results in ascending order by start time. Default is descending (newest first).

        limit : typing.Optional[int]
            The number of conversations to return per response.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConversationResponse
            Conversations retrieved successfully

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.conversation.list()
        """
        _response = self._raw_client.list(
            before=before, after=after, ascending=ascending, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data


class AsyncConversationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConversationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConversationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConversationClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        before: typing.Optional[dt.datetime] = None,
        after: typing.Optional[dt.datetime] = None,
        ascending: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConversationResponse:
        """
        Lists conversations (meetings) that occurred in your Roam, with participant details.

        **Access:**
        - **Organization with [`admin:meetings:read`](https://developer.ro.am/docs/guides/scopes#meeting-width-adminmeetingsread)**
          (or a grandfathered roam-wide API key): all conversations in the workspace.
        - **Personal access tokens:** supported — returns only conversations the
          token owner participated in (matched by confirmed email).
        - **Organization without roam-wide meeting access** must use
          [`/meeting.list`](https://developer.ro.am/docs/api/meeting-list) instead (`403`).

        **Required scope:** `meetings:read` (add `admin:meetings:read` for roam-wide org access)

        Participant details require `user:read` scope. Email addresses require `user:read.email` scope.

        Parameters
        ----------
        before : typing.Optional[dt.datetime]
            Only return conversations that started before this ISO-8601 timestamp.

        after : typing.Optional[dt.datetime]
            Only return conversations that started after this ISO-8601 timestamp.

        ascending : typing.Optional[bool]
            Sort results in ascending order by start time. Default is descending (newest first).

        limit : typing.Optional[int]
            The number of conversations to return per response.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConversationResponse
            Conversations retrieved successfully

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.conversation.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            before=before, after=after, ascending=ascending, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data
