# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class ListLobbyResponseLobbiesItem(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier of the lobby configuration (UUID)
    """

    slug: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional second path segment for the lobby. May be empty.
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="displayName"),
        pydantic.Field(alias="displayName", description="Human-readable name of the lobby configuration"),
    ] = None
    """
    Human-readable name of the lobby configuration
    """

    active: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the lobby configuration is active
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public URL of the lobby (e.g., `https://ro.am/handle` or `https://ro.am/handle/slug`)
    """

    handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    First path segment of the lobby URL
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
