# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

AddressType = typing.Union[
    typing.Literal["user", "bot", "standardGroup", "meetingGroup", "userGroup", "teamRoam"], typing.Any
]
