# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .address_type import AddressType


class Address(UniversalBaseModel):
    """
    A resolved address. Which fields are populated depends on `type`: `user`
    addresses include `email`/`isGuest`; `bot` addresses include
    `botCode`/`integrationId` when available; group addresses include only the
    common fields. Classic bots, agents, assistants, and coworkers all project
    as `type: bot`.
    """

    id: str = pydantic.Field()
    """
    The address ID.
    """

    type: AddressType = pydantic.Field()
    """
    The kind of address.
    """

    display_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="displayName"),
        pydantic.Field(alias="displayName", description="Display name of the address."),
    ] = None
    """
    Display name of the address.
    """

    display_image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="displayImageUrl"),
        pydantic.Field(alias="displayImageUrl", description="Display image URL of the address."),
    ] = None
    """
    Display image URL of the address.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address. Present on `user` addresses, and only when the token has the `user:read.email` scope.
    """

    is_guest: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isGuest"),
        pydantic.Field(
            alias="isGuest",
            description="Present and true only when the user has no membership in the caller's account.",
        ),
    ] = None
    """
    Present and true only when the user has no membership in the caller's account.
    """

    bot_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="botCode"),
        pydantic.Field(
            alias="botCode",
            description="Classic bot persona identifier, when available. Other bot-like actors may omit it.",
        ),
    ] = None
    """
    Classic bot persona identifier, when available. Other bot-like actors may omit it.
    """

    integration_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="integrationId"),
        pydantic.Field(
            alias="integrationId", description="Integration/client ID, when available. Some bot-like actors omit it."
        ),
    ] = None
    """
    Integration/client ID, when available. Some bot-like actors omit it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
