# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .chat_item import ChatItem
from .chat_message_content_type import ChatMessageContentType
from .chat_message_poll import ChatMessagePoll
from .chat_message_sender import ChatMessageSender
from .chat_message_type import ChatMessageType
from .chat_message_user_type import ChatMessageUserType
from .chat_message_voice import ChatMessageVoice


class ChatMessage(UniversalBaseModel):
    """
    A chat message in the Roam workspace
    """

    type: typing.Optional[ChatMessageType] = pydantic.Field(default=None)
    """
    Message type identifier
    """

    user_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="userId"),
        pydantic.Field(alias="userId", description="Principal ID of the message sender. Resolve with `user.info`."),
    ]
    """
    Principal ID of the message sender. Resolve with `user.info`.
    """

    user_type: typing_extensions.Annotated[
        ChatMessageUserType,
        FieldMetadata(alias="userType"),
        pydantic.Field(
            alias="userType",
            description="Principal type of `userId`; always equals `user.info.type` for the same credentials. Use it to prevent bot loops without another lookup.",
        ),
    ]
    """
    Principal type of `userId`; always equals `user.info.type` for the same credentials. Use it to prevent bot loops without another lookup.
    """

    chat_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="chatId"),
        pydantic.Field(alias="chatId", description="ID of the chat the message belongs to"),
    ] = None
    """
    ID of the chat the message belongs to
    """

    timestamp: int = pydantic.Field()
    """
    Message key as Unix microseconds
    """

    thread_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="threadTimestamp"),
        pydantic.Field(
            alias="threadTimestamp",
            description="Unix microseconds timestamp of the parent message (for thread replies)",
        ),
    ] = None
    """
    Unix microseconds timestamp of the parent message (for thread replies)
    """

    reply_timestamp: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="replyTimestamp"),
        pydantic.Field(
            alias="replyTimestamp",
            description="Timestamp of the message this one quotes — a DM or channel-thread quoted reply, set via the `replyTimestamp` request field on chat.post. Omitted otherwise.",
        ),
    ] = None
    """
    Timestamp of the message this one quotes — a DM or channel-thread quoted reply, set via the `replyTimestamp` request field on chat.post. Omitted otherwise.
    """

    ephemeral: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the message is ephemeral. Always omitted (false) in chat.history, chat.search, and chat.link.resolve responses — ephemeral messages (posted via chat.postEphemeral) are never persisted, so they never appear in these APIs.
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Text of the message, formatted as github-flavored markdown. Mention tokens use Slack's syntax: `<@ID>` is a principal (user or bot — resolve with `user.info`), `<!subteam^ID>` is a group or channel (resolve with `group.info`), and `<!channel>` is the broadcast keyword.
    """

    content_type: typing_extensions.Annotated[
        ChatMessageContentType,
        FieldMetadata(alias="contentType"),
        pydantic.Field(
            alias="contentType",
            description="Type of message content: `text` (markdown body, optionally with items), `voice` (voice note), `block` (rich block layout), or `poll`.",
        ),
    ]
    """
    Type of message content: `text` (markdown body, optionally with items), `voice` (voice note), `block` (rich block layout), or `poll`.
    """

    items: typing.Optional[typing.List[ChatItem]] = pydantic.Field(default=None)
    """
    Items attached to this message
    """

    poll: typing.Optional[ChatMessagePoll] = pydantic.Field(default=None)
    """
    Poll content, present when contentType is `poll`.
    """

    voice: typing.Optional[ChatMessageVoice] = pydantic.Field(default=None)
    """
    Voice-note content, present when contentType is `voice`.
    """

    blocks: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Rich block layout, present when contentType is `block`.
    """

    color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Accent color for a block message, present when contentType is `block`. Omitted otherwise.
    """

    reply_count: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="replyCount"),
        pydantic.Field(
            alias="replyCount", description="Number of replies in this message's thread. Omitted when zero."
        ),
    ] = None
    """
    Number of replies in this message's thread. Omitted when zero.
    """

    sender: typing.Optional[ChatMessageSender] = pydantic.Field(default=None)
    """
    Per-message sender display override supplied at send time via the
    request's `sender` field. Present only when the stored message carries
    one. Additive: `userId` remains the authoring identity — render the
    override, attribute with `userId`. See the
    [Sender Profiles guide](https://developer.ro.am/docs/guides/sender-profiles).
    """

    mentions: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Flat, order-preserving, de-duplicated list of everything referenced by
    mention tokens in `text`: bare address UUIDs (from both `<@ID>` principal
    and `<!subteam^ID>` group tokens), plus the literal `all` for the `<!channel>`
    broadcast keyword. Present when the text contains mentions. Resolve UUIDs
    to display info via the response's `addresses` map (request
    `expand=addresses`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
