# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .chat_message_poll_options_item import ChatMessagePollOptionsItem


class ChatMessagePoll(UniversalBaseModel):
    """
    Poll content, present when contentType is `poll`.
    """

    question: typing.Optional[str] = pydantic.Field(default=None)
    """
    The poll question.
    """

    options: typing.Optional[typing.List[ChatMessagePollOptionsItem]] = pydantic.Field(default=None)
    """
    The poll answer options.
    """

    allow_multiple_answers: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="allowMultipleAnswers"),
        pydantic.Field(alias="allowMultipleAnswers", description="Whether voters can select multiple options."),
    ] = None
    """
    Whether voters can select multiple options.
    """

    closes_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="closesAt"),
        pydantic.Field(
            alias="closesAt", description="When the poll closes (RFC-3339). Omitted if no close time is set."
        ),
    ] = None
    """
    When the poll closes (RFC-3339). Omitted if no close time is set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
