# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .group_member_role import GroupMemberRole


class GroupMember(UniversalBaseModel):
    """
    A member of a group with their role
    """

    user_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="userId"), pydantic.Field(alias="userId", description="The user's unique identifier")
    ]
    """
    The user's unique identifier
    """

    role: GroupMemberRole = pydantic.Field()
    """
    The member's role in the group
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
