# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

LobbyBookingResponseType = typing.Union[
    typing.Literal["short_text", "text", "email", "phone_number", "radio", "checkbox", "dropdown", "hidden"], typing.Any
]
