# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MagicastCue(UniversalBaseModel):
    """
    One transcribed sentence. Magicast transcripts are not speaker-diarized,
    so there is no `speaker` field (unlike meeting `transcript.info` cues).
    """

    text: str = pydantic.Field()
    """
    The transcribed text.
    """

    start_offset: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="startOffset"),
        pydantic.Field(
            alias="startOffset", description="Milliseconds from the start of the recording when the sentence began."
        ),
    ]
    """
    Milliseconds from the start of the recording when the sentence began.
    """

    end_offset: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="endOffset"),
        pydantic.Field(
            alias="endOffset", description="Milliseconds from the start of the recording when the sentence ended."
        ),
    ]
    """
    Milliseconds from the start of the recording when the sentence ended.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
