# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

MeetingParticipantType = typing.Union[typing.Literal["member", "guest"], typing.Any]
