# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_activity_display_color import UserActivityDisplayColor


class UserActivityDisplay(UniversalBaseModel):
    """
    What the map renders for this activity: a seat badge, hover tooltip, and
    optional glow. Limits count Unicode code points (runes), not bytes.
    """

    emoji: str = pydantic.Field()
    """
    Badge shown on the user's seat. Required. Must be a single emoji —
    a text blurb or several emoji is `invalid_parameter`. ZWJ sequences
    (family, flags, keycaps, skin tones) count as one. At most 16
    Unicode code points (the storage cap).
    """

    title: str = pydantic.Field()
    """
    Required hover-tooltip title. At most 140 Unicode code points.
    """

    subtitle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional supporting line after the title (for example the source app
    and a customer name). At most 140 Unicode code points. Omitted when
    empty.
    """

    color: typing.Optional[UserActivityDisplayColor] = pydantic.Field(default=None)
    """
    Curated glow palette name. Omit (or send empty) for a quiet badge-only
    activity. Unknown names are rejected at set time. Clients resolve the
    name to light/dark hex — hex is not part of the API. First-party agent
    glows (Claude, Codex, Pi, room agents) are not in this palette.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
