# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class UserStatusBubbleResponseStatusBubble(UniversalBaseModel):
    """
    The live thought bubble, or null when none is set or it has expired.
    """

    text: str = pydantic.Field()
    """
    Trimmed text, limited to 20 Unicode code points.
    """

    expires_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(
            alias="expiresAt", description="Server-stamped expiration in RFC3339 format with millisecond precision."
        ),
    ]
    """
    Server-stamped expiration in RFC3339 format with millisecond precision.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
