# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .user_status import UserStatus
from .user_type import UserType
from .user_will_return import UserWillReturn


class User(UniversalBaseModel):
    """
    A v1 acting principal. Workspace members and guests have `type: user`;
    classic bots, agents, assistants, and coworkers have `type: bot`.
    See [Identity & Principals](https://developer.ro.am/docs/guides/identity-and-principals).
    """

    id: str = pydantic.Field()
    """
    The principal's unique address identifier.
    """

    type: UserType = pydantic.Field()
    """
    Stable public principal type. All automated actors are `bot`.
    """

    name: str = pydantic.Field()
    """
    Display name of the principal.
    """

    image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageUrl"),
        pydantic.Field(alias="imageUrl", description="URL of the principal's profile image."),
    ] = None
    """
    URL of the principal's profile image.
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address for a member or guest (requires `user:read.email`). Omitted for bots.
    """

    is_guest: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isGuest"),
        pydantic.Field(
            alias="isGuest", description="Present and true only for users without membership in the caller's account."
        ),
    ] = None
    """
    Present and true only for users without membership in the caller's account.
    """

    is_admin: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isAdmin"),
        pydantic.Field(
            alias="isAdmin",
            description="Whether a workspace member is an admin. Present for members even when false; omitted for guests and bots.",
        ),
    ] = None
    """
    Whether a workspace member is an admin. Present for members even when false; omitted for guests and bots.
    """

    job_title: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="jobTitle"),
        pydantic.Field(alias="jobTitle", description="Workspace member's job title. Omitted for guests and bots."),
    ] = None
    """
    Workspace member's job title. Omitted for guests and bots.
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workspace member's location. Omitted for guests and bots.
    """

    status: typing.Optional[UserStatus] = pydantic.Field(default=None)
    """
    User's current presence status. Only included when `expand=status` is requested and the `user:read.status` scope is granted.
    """

    will_return: typing_extensions.Annotated[
        typing.Optional[UserWillReturn],
        FieldMetadata(alias="willReturn"),
        pydantic.Field(
            alias="willReturn",
            description='Out-of-office / "Will Return" status. Present only when `expand=status` is requested, the `user:read.status` scope is granted, and the user has a future return time. A user can be `checkedIn` and still have `willReturn` (multi-day Out of Roam) — key off the presence of this object rather than `status` alone.',
        ),
    ] = None
    """
    Out-of-office / "Will Return" status. Present only when `expand=status` is requested, the `user:read.status` scope is granted, and the user has a future return time. A user can be `checkedIn` and still have `willReturn` (multi-day Out of Roam) — key off the presence of this object rather than `status` alone.
    """

    available: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the user is currently available for visitors. Only included when `expand=available` is requested and the `user:read.status` scope is granted.
    """

    bot_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="botCode"),
        pydantic.Field(alias="botCode", description="Classic bot persona identifier, when available."),
    ] = None
    """
    Classic bot persona identifier, when available.
    """

    integration_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="integrationId"),
        pydantic.Field(
            alias="integrationId", description="Integration/client identifier for an automated actor, when available."
        ),
    ] = None
    """
    Integration/client identifier for an automated actor, when available.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
