# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class UserWillReturn(UniversalBaseModel):
    """
    Out-of-office / "Will Return" status. Present only when `expand=status` is requested, the `user:read.status` scope is granted, and the user has a future return time. A user can be `checkedIn` and still have `willReturn` (multi-day Out of Roam) — key off the presence of this object rather than `status` alone.
    """

    return_time: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="returnTime"),
        pydantic.Field(alias="returnTime", description="When the user is expected to return (RFC 3339)."),
    ]
    """
    When the user is expected to return (RFC 3339).
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional absence message (e.g. "On Vacation").
    """

    out_of_roam: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="outOfRoam"),
        pydantic.Field(
            alias="outOfRoam",
            description="When true, multi-day Out of Roam that persists across check-ins. When false or omitted, same-day Will Return Today.",
        ),
    ] = None
    """
    When true, multi-day Out of Roam that persists across check-ins. When false or omitted, same-day Will Return Today.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
