# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_destination_type import WebhookDestinationType


class WebhookDestination(UniversalBaseModel):
    """
    Delivery authentication. Omitted for Standard Webhooks (the default).
    `type` is `grok_bot` when the subscription was created with
    `destination.type=grok_bot`. The sender key is never returned.
    """

    type: typing.Optional[WebhookDestinationType] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
