# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

WebhookEvent = typing.Union[
    typing.Literal[
        "chat.message",
        "chat.reaction",
        "chat.link.shared",
        "lobby.booked",
        "magicast.created",
        "meeting.started",
        "meeting.ended",
        "user.status.update",
        "onair.event.created",
        "onair.event.updated",
        "onair.event.canceled",
        "onair.guest.rsvp",
        "onair.guest.added",
        "token.revoked",
        "app.uninstalled",
    ],
    typing.Any,
]
