# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

WebhookSubscriptionFilterChatType = typing.Union[typing.Literal["dm", "group"], typing.Any]
