# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from __future__ import annotations

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AppendStreamChatResponse,
        CancelScheduledChatResponse,
        CreateLinkChatResponse,
        DeleteChatResponse,
        HistoryChatResponse,
        ListChatResponse,
        ListChatResponseChatsItem,
        ListChatResponseChatsItemPreview,
        ListChatResponseChatsItemPreviewContentType,
        ListChatResponseChatsItemPreviewSender,
        ListChatResponseChatsItemType,
        ListScheduledChatResponse,
        ListScheduledChatResponseScheduledMessagesItem,
        PostChatRequestBlocksItem,
        PostChatRequestBlocksItemType,
        PostChatRequestPoll,
        PostChatResponse,
        PostEphemeralChatResponse,
        ResolveLinkChatResponse,
        SearchChatRequestChatTypesItem,
        SearchChatRequestHasItem,
        SearchChatRequestSort,
        SearchChatResponse,
        StartStreamChatRequestKind,
        StartStreamChatResponse,
        StopStreamChatResponse,
        TypingChatRequestSender,
        UnfurlChatResponse,
        UpdateChatRequestBlocksItem,
        UpdateChatRequestBlocksItemType,
        UpdateChatResponse,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "AppendStreamChatResponse": ".types",
    "CancelScheduledChatResponse": ".types",
    "CreateLinkChatResponse": ".types",
    "DeleteChatResponse": ".types",
    "HistoryChatResponse": ".types",
    "ListChatResponse": ".types",
    "ListChatResponseChatsItem": ".types",
    "ListChatResponseChatsItemPreview": ".types",
    "ListChatResponseChatsItemPreviewContentType": ".types",
    "ListChatResponseChatsItemPreviewSender": ".types",
    "ListChatResponseChatsItemType": ".types",
    "ListScheduledChatResponse": ".types",
    "ListScheduledChatResponseScheduledMessagesItem": ".types",
    "PostChatRequestBlocksItem": ".types",
    "PostChatRequestBlocksItemType": ".types",
    "PostChatRequestPoll": ".types",
    "PostChatResponse": ".types",
    "PostEphemeralChatResponse": ".types",
    "ResolveLinkChatResponse": ".types",
    "SearchChatRequestChatTypesItem": ".types",
    "SearchChatRequestHasItem": ".types",
    "SearchChatRequestSort": ".types",
    "SearchChatResponse": ".types",
    "StartStreamChatRequestKind": ".types",
    "StartStreamChatResponse": ".types",
    "StopStreamChatResponse": ".types",
    "TypingChatRequestSender": ".types",
    "UnfurlChatResponse": ".types",
    "UpdateChatRequestBlocksItem": ".types",
    "UpdateChatRequestBlocksItemType": ".types",
    "UpdateChatResponse": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AppendStreamChatResponse",
    "CancelScheduledChatResponse",
    "CreateLinkChatResponse",
    "DeleteChatResponse",
    "HistoryChatResponse",
    "ListChatResponse",
    "ListChatResponseChatsItem",
    "ListChatResponseChatsItemPreview",
    "ListChatResponseChatsItemPreviewContentType",
    "ListChatResponseChatsItemPreviewSender",
    "ListChatResponseChatsItemType",
    "ListScheduledChatResponse",
    "ListScheduledChatResponseScheduledMessagesItem",
    "PostChatRequestBlocksItem",
    "PostChatRequestBlocksItemType",
    "PostChatRequestPoll",
    "PostChatResponse",
    "PostEphemeralChatResponse",
    "ResolveLinkChatResponse",
    "SearchChatRequestChatTypesItem",
    "SearchChatRequestHasItem",
    "SearchChatRequestSort",
    "SearchChatResponse",
    "StartStreamChatRequestKind",
    "StartStreamChatResponse",
    "StopStreamChatResponse",
    "TypingChatRequestSender",
    "UnfurlChatResponse",
    "UpdateChatRequestBlocksItem",
    "UpdateChatRequestBlocksItemType",
    "UpdateChatResponse",
]
