# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .list_conversation_response_conversations_item_participants_item import (
    ListConversationResponseConversationsItemParticipantsItem,
)


class ListConversationResponseConversationsItem(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the conversation (meeting GUID)
    """

    place: typing.Optional[str] = pydantic.Field(default=None)
    """
    The place where the conversation occurred
    """

    room: typing.Optional[str] = pydantic.Field(default=None)
    """
    The room name
    """

    room_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="roomType"),
        pydantic.Field(alias="roomType", description="The type of room"),
    ] = None
    """
    The type of room
    """

    start: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the conversation started (ISO-8601)
    """

    end: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the conversation ended (ISO-8601)
    """

    participants: typing.Optional[typing.List[ListConversationResponseConversationsItemParticipantsItem]] = (
        pydantic.Field(default=None)
    )
    """
    List of participants (requires `user:read` scope)
    """

    meeting_link_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="meetingLinkIds"),
        pydantic.Field(alias="meetingLinkIds", description="IDs of meeting links associated with this conversation"),
    ] = None
    """
    IDs of meeting links associated with this conversation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
