# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListConversationResponseConversationsItemParticipantsItem(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of the participant
    """

    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email address (requires `user:read.email` scope)
    """

    seconds: typing.Optional[float] = pydantic.Field(default=None)
    """
    Duration the participant was in the conversation, in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
