# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class UserStatusSetRequestWillReturn(UniversalBaseModel):
    """
    Absence to write. Required. Replaces any existing Will
    Return / Out of Roam on this user.
    """

    return_time: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="returnTime"),
        pydantic.Field(
            alias="returnTime",
            description="When the user is expected back (RFC3339). Must be in\nthe future and at most 2 years from now. Will Return\nToday (`outOfRoam: false`) additionally requires\nless than 10 hours from now.",
        ),
    ]
    """
    When the user is expected back (RFC3339). Must be in
    the future and at most 2 years from now. Will Return
    Today (`outOfRoam: false`) additionally requires
    less than 10 hours from now.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional absence message (for example "On vacation").
    At most 128 Unicode code points.
    """

    out_of_roam: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="outOfRoam"),
        pydantic.Field(
            alias="outOfRoam",
            description="`true` (default) is multi-day Out of Roam and persists\nacross check-ins. `false` is same-day Will Return Today.",
        ),
    ] = None
    """
    `true` (default) is multi-day Out of Roam and persists
    across check-ins. `false` is same-day Will Return Today.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
