# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error import Error
from ..types.webhook import Webhook
from ..types.webhook_subscription_filter import WebhookSubscriptionFilter
from .types.deliveries_webhook_response import DeliveriesWebhookResponse
from .types.list_webhook_response import ListWebhookResponse
from .types.webhook_subscription_request_event import WebhookSubscriptionRequestEvent
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWebhookClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[ListWebhookResponse]:
        """
        List all webhook subscriptions owned by the authenticated API client.

        The response includes both **dynamic** subscriptions (created via
        [`/webhook.subscribe`](https://developer.ro.am/docs/webhooks/webhook-subscribe)) and **static**
        subscriptions configured in the Roam Administration UI.

        Each object may include `lastSuccessAt`, `failStreakStartedAt`, and
        `disabledAt` (omitted when null). `disabledAt` means the destination is
        paused. See [Subscription health](https://developer.ro.am/docs/webhooks/webhooks#subscription-health).

        **Required scope:** `webhook:read`

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListWebhookResponse]
            List of webhook subscriptions.
        """
        _response = self._client_wrapper.httpx_client.request(
            "webhook.list",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListWebhookResponse,
                    parse_obj_as(
                        type_=ListWebhookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def subscribe(
        self,
        *,
        url: str,
        event: WebhookSubscriptionRequestEvent,
        filter: typing.Optional[WebhookSubscriptionFilter] = OMIT,
        api_version: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Webhook]:
        """
        Create or update a webhook subscription for a given event. If a subscription
        already exists for the same event and URL, its filter is updated instead of
        creating a duplicate. Re-subscribing the same event and URL also clears a
        pause (`disabledAt` / `failStreakStartedAt`) so deliveries resume on the
        next event. See [Subscription health](https://developer.ro.am/docs/webhooks/webhooks#subscription-health).

        **Event names are dotted:** `chat.message`, `lobby.booked`,
        `magicast.created`. Colon names (`chat:message:dm`, `lobby:booked`) are
        v0-only — sending them here returns `400` / `Unrecognized event`.

        Roam does not probe the destination URL when you subscribe — the
        subscription is created immediately and the first delivery is a real event.

        Optional `filter` limits which occurrences are delivered. Which keys are
        valid depends on `event` — see that event's page and the
        [Event Filters](https://developer.ro.am/docs/webhooks/webhooks#event-filters) table. Omit
        `filter` to receive every occurrence. An empty object (`{}`) is rejected,
        as is a filter that does not apply to the event.

        **DMs only:**

        ```json
        {
          "url": "https://example.com/hooks/messages",
          "event": "chat.message",
          "filter": { "chatType": "dm" }
        }
        ```

        **Required scope:** `webhook:write`

        Parameters
        ----------
        url : str
            Destination URL for webhook deliveries (max 1024 characters). HTTPS is required outside local environments.

        event : WebhookSubscriptionRequestEvent
            Event to subscribe to.

        filter : typing.Optional[WebhookSubscriptionFilter]
            Optional event-specific filter. Which keys are valid depends on `event`
            (see the schema). Omit to receive every occurrence; `{}` and `null` are
            rejected rather than treated as "omitted". Example for DMs only:
            `{"chatType": "dm"}`.

        api_version : typing.Optional[str]
            Optional [API version](https://developer.ro.am/docs/guides/api-versioning) (`YYYY-MM-DD`) to pin
            this subscription's payload shape to. When omitted, the subscription is
            frozen at your integration's default version. Unsupported values return
            `400`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Webhook]
            Subscription created or updated.
        """
        _response = self._client_wrapper.httpx_client.request(
            "webhook.subscribe",
            method="POST",
            json={
                "url": url,
                "event": event,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=WebhookSubscriptionFilter, direction="write"
                ),
                "apiVersion": api_version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Webhook,
                    parse_obj_as(
                        type_=Webhook,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def unsubscribe(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[None]:
        """
        Remove a webhook subscription by ID.

        The request body is JSON: `{"id": "<subscription uuid>"}`. This differs
        from v0, which expects `application/x-www-form-urlencoded` with the same
        `id` field. Sending JSON to `/v0/webhook.unsubscribe` returns
        `id parameter required`.

        **Required scope:** `webhook:write`

        Parameters
        ----------
        id : str
            Identifier of the webhook subscription to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            "webhook.unsubscribe",
            method="POST",
            json={
                "id": id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def deliveries(
        self,
        *,
        webhook: typing.Optional[str] = None,
        event: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DeliveriesWebhookResponse]:
        """
        List recent **failed** webhook delivery attempts for the authenticated API
        client, newest first. Use this to debug a misbehaving endpoint and to find
        the events you need to replay: successful (2xx) deliveries are never
        recorded, so every row here is a delivery your endpoint did not accept.

        Timeouts are first-class failures: `statusCode` is `0` and `error` is
        `timeout`. For HTTP error responses, a truncated copy of your server's
        response body is included to aid debugging. The request payload is never
        stored — to recover the data, re-fetch the underlying resource (e.g. via
        `chat.history`) using the delivery's `messageId`/`event` context.

        Results are strictly scoped to the caller's own subscriptions and retained
        for roughly 30 days.

        **Access:** Organization and Personal.

        **Required scope:** `webhook:read`

        Parameters
        ----------
        webhook : typing.Optional[str]
            Only return deliveries for this webhook subscription ID.

        event : typing.Optional[str]
            Only return deliveries for this event name (e.g. `chat.message`).

        after : typing.Optional[str]
            Only return deliveries after this time (RFC3339 or `YYYY-MM-DD`). Results switch to oldest-first.

        before : typing.Optional[str]
            Only return deliveries before this time (RFC3339 or `YYYY-MM-DD`).

        limit : typing.Optional[int]
            Maximum number of deliveries to return.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeliveriesWebhookResponse]
            Failed delivery attempts for the caller's subscriptions.
        """
        _response = self._client_wrapper.httpx_client.request(
            "webhook.deliveries",
            method="GET",
            params={
                "webhook": webhook,
                "event": event,
                "after": after,
                "before": before,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeliveriesWebhookResponse,
                    parse_obj_as(
                        type_=DeliveriesWebhookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWebhookClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListWebhookResponse]:
        """
        List all webhook subscriptions owned by the authenticated API client.

        The response includes both **dynamic** subscriptions (created via
        [`/webhook.subscribe`](https://developer.ro.am/docs/webhooks/webhook-subscribe)) and **static**
        subscriptions configured in the Roam Administration UI.

        Each object may include `lastSuccessAt`, `failStreakStartedAt`, and
        `disabledAt` (omitted when null). `disabledAt` means the destination is
        paused. See [Subscription health](https://developer.ro.am/docs/webhooks/webhooks#subscription-health).

        **Required scope:** `webhook:read`

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListWebhookResponse]
            List of webhook subscriptions.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "webhook.list",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListWebhookResponse,
                    parse_obj_as(
                        type_=ListWebhookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def subscribe(
        self,
        *,
        url: str,
        event: WebhookSubscriptionRequestEvent,
        filter: typing.Optional[WebhookSubscriptionFilter] = OMIT,
        api_version: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Webhook]:
        """
        Create or update a webhook subscription for a given event. If a subscription
        already exists for the same event and URL, its filter is updated instead of
        creating a duplicate. Re-subscribing the same event and URL also clears a
        pause (`disabledAt` / `failStreakStartedAt`) so deliveries resume on the
        next event. See [Subscription health](https://developer.ro.am/docs/webhooks/webhooks#subscription-health).

        **Event names are dotted:** `chat.message`, `lobby.booked`,
        `magicast.created`. Colon names (`chat:message:dm`, `lobby:booked`) are
        v0-only — sending them here returns `400` / `Unrecognized event`.

        Roam does not probe the destination URL when you subscribe — the
        subscription is created immediately and the first delivery is a real event.

        Optional `filter` limits which occurrences are delivered. Which keys are
        valid depends on `event` — see that event's page and the
        [Event Filters](https://developer.ro.am/docs/webhooks/webhooks#event-filters) table. Omit
        `filter` to receive every occurrence. An empty object (`{}`) is rejected,
        as is a filter that does not apply to the event.

        **DMs only:**

        ```json
        {
          "url": "https://example.com/hooks/messages",
          "event": "chat.message",
          "filter": { "chatType": "dm" }
        }
        ```

        **Required scope:** `webhook:write`

        Parameters
        ----------
        url : str
            Destination URL for webhook deliveries (max 1024 characters). HTTPS is required outside local environments.

        event : WebhookSubscriptionRequestEvent
            Event to subscribe to.

        filter : typing.Optional[WebhookSubscriptionFilter]
            Optional event-specific filter. Which keys are valid depends on `event`
            (see the schema). Omit to receive every occurrence; `{}` and `null` are
            rejected rather than treated as "omitted". Example for DMs only:
            `{"chatType": "dm"}`.

        api_version : typing.Optional[str]
            Optional [API version](https://developer.ro.am/docs/guides/api-versioning) (`YYYY-MM-DD`) to pin
            this subscription's payload shape to. When omitted, the subscription is
            frozen at your integration's default version. Unsupported values return
            `400`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Webhook]
            Subscription created or updated.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "webhook.subscribe",
            method="POST",
            json={
                "url": url,
                "event": event,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=WebhookSubscriptionFilter, direction="write"
                ),
                "apiVersion": api_version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Webhook,
                    parse_obj_as(
                        type_=Webhook,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def unsubscribe(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Remove a webhook subscription by ID.

        The request body is JSON: `{"id": "<subscription uuid>"}`. This differs
        from v0, which expects `application/x-www-form-urlencoded` with the same
        `id` field. Sending JSON to `/v0/webhook.unsubscribe` returns
        `id parameter required`.

        **Required scope:** `webhook:write`

        Parameters
        ----------
        id : str
            Identifier of the webhook subscription to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "webhook.unsubscribe",
            method="POST",
            json={
                "id": id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def deliveries(
        self,
        *,
        webhook: typing.Optional[str] = None,
        event: typing.Optional[str] = None,
        after: typing.Optional[str] = None,
        before: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DeliveriesWebhookResponse]:
        """
        List recent **failed** webhook delivery attempts for the authenticated API
        client, newest first. Use this to debug a misbehaving endpoint and to find
        the events you need to replay: successful (2xx) deliveries are never
        recorded, so every row here is a delivery your endpoint did not accept.

        Timeouts are first-class failures: `statusCode` is `0` and `error` is
        `timeout`. For HTTP error responses, a truncated copy of your server's
        response body is included to aid debugging. The request payload is never
        stored — to recover the data, re-fetch the underlying resource (e.g. via
        `chat.history`) using the delivery's `messageId`/`event` context.

        Results are strictly scoped to the caller's own subscriptions and retained
        for roughly 30 days.

        **Access:** Organization and Personal.

        **Required scope:** `webhook:read`

        Parameters
        ----------
        webhook : typing.Optional[str]
            Only return deliveries for this webhook subscription ID.

        event : typing.Optional[str]
            Only return deliveries for this event name (e.g. `chat.message`).

        after : typing.Optional[str]
            Only return deliveries after this time (RFC3339 or `YYYY-MM-DD`). Results switch to oldest-first.

        before : typing.Optional[str]
            Only return deliveries before this time (RFC3339 or `YYYY-MM-DD`).

        limit : typing.Optional[int]
            Maximum number of deliveries to return.

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeliveriesWebhookResponse]
            Failed delivery attempts for the caller's subscriptions.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "webhook.deliveries",
            method="GET",
            params={
                "webhook": webhook,
                "event": event,
                "after": after,
                "before": before,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeliveriesWebhookResponse,
                    parse_obj_as(
                        type_=DeliveriesWebhookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
