# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawGroupsClient, RawGroupsClient
from .types.groups_list_response_item import GroupsListResponseItem


class GroupsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawGroupsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawGroupsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawGroupsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[GroupsListResponseItem]:
        """
        **Legacy:** Prefer [`/group.list`](https://developer.ro.am/docs/api/group-list) for new integrations.

        Lists all public, non-archived groups in your home Roam.

        Unlike `/group.list`, this endpoint returns a **raw JSON array** (not the
        `{"ok": true, …}` envelope). It is the sole ok-envelope exception on `/v1`
        and remains only for existing callers.

        **Access:** Organization only.

        **Required scope:** `group:read`

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GroupsListResponseItem]
            OK. **Note:** response is a raw array, not the v1 `ok` envelope.

        Examples
        --------
        from roamhq import RoamClient

        client = RoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )
        client.groups.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data


class AsyncGroupsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawGroupsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawGroupsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawGroupsClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[GroupsListResponseItem]:
        """
        **Legacy:** Prefer [`/group.list`](https://developer.ro.am/docs/api/group-list) for new integrations.

        Lists all public, non-archived groups in your home Roam.

        Unlike `/group.list`, this endpoint returns a **raw JSON array** (not the
        `{"ok": true, …}` envelope). It is the sole ok-envelope exception on `/v1`
        and remains only for existing callers.

        **Access:** Organization only.

        **Required scope:** `group:read`

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[GroupsListResponseItem]
            OK. **Note:** response is a raw array, not the v1 `ok` envelope.

        Examples
        --------
        import asyncio

        from roamhq import AsyncRoamClient

        client = AsyncRoamClient(
            roam_version="YOUR_ROAM_VERSION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.groups.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data
