# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.method_not_allowed_error import MethodNotAllowedError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error import Error
from ..types.guest_badge import GuestBadge
from .types.guest_badge_list_response import GuestBadgeListResponse
from .types.guest_badge_revoke_response import GuestBadgeRevokeResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawGuestBadgesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def guest_badge_create(
        self,
        *,
        email: str,
        host_user_id: typing.Optional[str] = OMIT,
        visit_permission: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GuestBadge]:
        """
        Grant a Guest Badge so an email that is **not** a workspace member can
        visit a host in Roam.

        This is **not** an [On-Air event guest](https://developer.ro.am/docs/onair-api/on-air-api). It is
        also **not** implied by [`group.add`](https://developer.ro.am/docs/api/group-add): adding an email
        to a group does not mint a badge or send the invite. Typical onboarding is
        `guest.badge.create` then `group.add`.

        Repeating create for the same host and email returns the existing badge
        (`visitPermission` is **not** updated) and does not re-send the invite.
        To flip on-map access after create, use
        [`guest.badge.update`](https://developer.ro.am/docs/api/guest-badge-update).

        **Access:** Organization and Personal.
        Organization tokens require `hostUserId`. Personal tokens default to the
        token owner; naming a different host returns `403` `access_mode_not_supported`.

        **Required scope:** `guest:write`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : str
            Guest email. ASCII only. Must not be a workspace member.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email — the same convention as
            [`group.create`](https://developer.ro.am/docs/api/group-create) `members[].userId`.
            Required for organization tokens. Optional for personal tokens
            (defaults to the token owner).

        visit_permission : typing.Optional[bool]
            Whether the guest may visit the host on the map. Defaults to
            `true`. Ignored on an idempotent retry of an existing grant
            — use [`guest.badge.update`](https://developer.ro.am/docs/api/guest-badge-update)
            to change it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GuestBadge]
            Badge created, or the existing grant returned.
        """
        _response = self._client_wrapper.httpx_client.request(
            "guest.badge.create",
            method="POST",
            json={
                "email": email,
                "hostUserId": host_user_id,
                "visitPermission": visit_permission,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadge,
                    parse_obj_as(
                        type_=GuestBadge,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def guest_badge_list(
        self,
        *,
        email: typing.Optional[str] = None,
        host_user_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GuestBadgeListResponse]:
        """
        List issued Guest Badges.

        Organization tokens return every issued badge in the workspace. Personal
        tokens return only badges the token owner issued. This is the issued
        (host) view — the same rows `guest.badge.create` returns — not the
        guest's hidden-inbox view.

        Filter with `email` (alias-aware) and/or `hostUserId` (UUID or member
        email). Paginate with `limit` / `cursor` (default 50, max 100). Results
        are sorted by `(hostUserId, email)`.

        Organization keys that only have `guest:write` must also request
        `guest:read` to call list. Personal Access Tokens with `pat:guests:write`
        already include `guest:read`.

        **Access:** Organization and Personal.
        Personal tokens naming a different host return `403`
        `access_mode_not_supported`.

        **Required scope:** `guest:read`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : typing.Optional[str]
            Guest email. ASCII only. Matches the stored address and its verified
            domain aliases.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email — the same convention as
            [`group.create`](https://developer.ro.am/docs/api/group-create) `members[].userId`.
            Archived hosts may be named (they typically have no remaining grants).
            Personal tokens may only pass the token owner.

        limit : typing.Optional[int]
            Number of badges to return per page (default 50, max 100).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GuestBadgeListResponse]
            Issued Guest Badges for this page.
        """
        _response = self._client_wrapper.httpx_client.request(
            "guest.badge.list",
            method="GET",
            params={
                "email": email,
                "hostUserId": host_user_id,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadgeListResponse,
                    parse_obj_as(
                        type_=GuestBadgeListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def guest_badge_update(
        self,
        *,
        email: str,
        visit_permission: bool,
        host_user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GuestBadge]:
        """
        Update `visitPermission` on an existing Guest Badge.

        [`guest.badge.create`](https://developer.ro.am/docs/api/guest-badge-create) is idempotent and
        does **not** change `visitPermission` on an existing grant. Use this
        endpoint to flip on-map visit access after create.

        If only one host in the workspace has granted this email, `hostUserId`
        may be omitted. If several hosts have, pass `hostUserId` to pick which
        grant to update (`400` `missing_parameter` otherwise). Same-host alias
        rows are updated together.

        Personal tokens can only update badges they issued. Naming another host
        is `403` `access_mode_not_supported`; omitting `hostUserId` when the
        token owner has no matching grant is `404` `not_found`.

        **Access:** Organization and Personal.

        **Required scope:** `guest:write`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : str
            Guest email. ASCII only.

        visit_permission : bool
            Whether the guest may visit the host on the map.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email. Required when more than one
            host has granted this email. Optional for a unique grant, and
            for personal tokens (defaults to the token owner).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GuestBadge]
            The updated Guest Badge.
        """
        _response = self._client_wrapper.httpx_client.request(
            "guest.badge.update",
            method="POST",
            json={
                "email": email,
                "hostUserId": host_user_id,
                "visitPermission": visit_permission,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadge,
                    parse_obj_as(
                        type_=GuestBadge,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def guest_badge_revoke(
        self,
        *,
        email: str,
        host_user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GuestBadgeRevokeResponse]:
        """
        Revoke Guest Badge(s) for an email.

        If only one host in the workspace has granted this email, `hostUserId` may
        be omitted. If several hosts have, pass `hostUserId` to pick which grant
        to revoke (`400` `missing_parameter` otherwise). Same-host alias rows are
        all revoked together.

        Returns `{ "revoked": true }` when a matching grant was found and deleted,
        or `{ "revoked": false }` when there was nothing to revoke (already gone,
        including after the host was archived — archiving a member deletes the
        badges they granted). Naming an archived host does not 404.

        Personal tokens can only revoke badges they issued. Naming another host is
        `403` `access_mode_not_supported`; omitting `hostUserId` when only another
        host granted the email is a no-op (`revoked: false`).

        **Access:** Organization and Personal.

        **Required scope:** `guest:write`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : str
            Guest email. ASCII only.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email. Required when more than one
            host has granted this email. Optional for a unique grant, and
            for personal tokens (defaults to the token owner).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GuestBadgeRevokeResponse]
            Revoke attempted. `revoked` is true only when a matching grant was deleted.
        """
        _response = self._client_wrapper.httpx_client.request(
            "guest.badge.revoke",
            method="POST",
            json={
                "email": email,
                "hostUserId": host_user_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadgeRevokeResponse,
                    parse_obj_as(
                        type_=GuestBadgeRevokeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawGuestBadgesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def guest_badge_create(
        self,
        *,
        email: str,
        host_user_id: typing.Optional[str] = OMIT,
        visit_permission: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GuestBadge]:
        """
        Grant a Guest Badge so an email that is **not** a workspace member can
        visit a host in Roam.

        This is **not** an [On-Air event guest](https://developer.ro.am/docs/onair-api/on-air-api). It is
        also **not** implied by [`group.add`](https://developer.ro.am/docs/api/group-add): adding an email
        to a group does not mint a badge or send the invite. Typical onboarding is
        `guest.badge.create` then `group.add`.

        Repeating create for the same host and email returns the existing badge
        (`visitPermission` is **not** updated) and does not re-send the invite.
        To flip on-map access after create, use
        [`guest.badge.update`](https://developer.ro.am/docs/api/guest-badge-update).

        **Access:** Organization and Personal.
        Organization tokens require `hostUserId`. Personal tokens default to the
        token owner; naming a different host returns `403` `access_mode_not_supported`.

        **Required scope:** `guest:write`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : str
            Guest email. ASCII only. Must not be a workspace member.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email — the same convention as
            [`group.create`](https://developer.ro.am/docs/api/group-create) `members[].userId`.
            Required for organization tokens. Optional for personal tokens
            (defaults to the token owner).

        visit_permission : typing.Optional[bool]
            Whether the guest may visit the host on the map. Defaults to
            `true`. Ignored on an idempotent retry of an existing grant
            — use [`guest.badge.update`](https://developer.ro.am/docs/api/guest-badge-update)
            to change it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GuestBadge]
            Badge created, or the existing grant returned.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "guest.badge.create",
            method="POST",
            json={
                "email": email,
                "hostUserId": host_user_id,
                "visitPermission": visit_permission,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadge,
                    parse_obj_as(
                        type_=GuestBadge,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def guest_badge_list(
        self,
        *,
        email: typing.Optional[str] = None,
        host_user_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GuestBadgeListResponse]:
        """
        List issued Guest Badges.

        Organization tokens return every issued badge in the workspace. Personal
        tokens return only badges the token owner issued. This is the issued
        (host) view — the same rows `guest.badge.create` returns — not the
        guest's hidden-inbox view.

        Filter with `email` (alias-aware) and/or `hostUserId` (UUID or member
        email). Paginate with `limit` / `cursor` (default 50, max 100). Results
        are sorted by `(hostUserId, email)`.

        Organization keys that only have `guest:write` must also request
        `guest:read` to call list. Personal Access Tokens with `pat:guests:write`
        already include `guest:read`.

        **Access:** Organization and Personal.
        Personal tokens naming a different host return `403`
        `access_mode_not_supported`.

        **Required scope:** `guest:read`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : typing.Optional[str]
            Guest email. ASCII only. Matches the stored address and its verified
            domain aliases.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email — the same convention as
            [`group.create`](https://developer.ro.am/docs/api/group-create) `members[].userId`.
            Archived hosts may be named (they typically have no remaining grants).
            Personal tokens may only pass the token owner.

        limit : typing.Optional[int]
            Number of badges to return per page (default 50, max 100).

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response's `nextCursor`. Do not construct cursors manually.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GuestBadgeListResponse]
            Issued Guest Badges for this page.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "guest.badge.list",
            method="GET",
            params={
                "email": email,
                "hostUserId": host_user_id,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadgeListResponse,
                    parse_obj_as(
                        type_=GuestBadgeListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def guest_badge_update(
        self,
        *,
        email: str,
        visit_permission: bool,
        host_user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GuestBadge]:
        """
        Update `visitPermission` on an existing Guest Badge.

        [`guest.badge.create`](https://developer.ro.am/docs/api/guest-badge-create) is idempotent and
        does **not** change `visitPermission` on an existing grant. Use this
        endpoint to flip on-map visit access after create.

        If only one host in the workspace has granted this email, `hostUserId`
        may be omitted. If several hosts have, pass `hostUserId` to pick which
        grant to update (`400` `missing_parameter` otherwise). Same-host alias
        rows are updated together.

        Personal tokens can only update badges they issued. Naming another host
        is `403` `access_mode_not_supported`; omitting `hostUserId` when the
        token owner has no matching grant is `404` `not_found`.

        **Access:** Organization and Personal.

        **Required scope:** `guest:write`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : str
            Guest email. ASCII only.

        visit_permission : bool
            Whether the guest may visit the host on the map.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email. Required when more than one
            host has granted this email. Optional for a unique grant, and
            for personal tokens (defaults to the token owner).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GuestBadge]
            The updated Guest Badge.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "guest.badge.update",
            method="POST",
            json={
                "email": email,
                "hostUserId": host_user_id,
                "visitPermission": visit_permission,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadge,
                    parse_obj_as(
                        type_=GuestBadge,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def guest_badge_revoke(
        self,
        *,
        email: str,
        host_user_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GuestBadgeRevokeResponse]:
        """
        Revoke Guest Badge(s) for an email.

        If only one host in the workspace has granted this email, `hostUserId` may
        be omitted. If several hosts have, pass `hostUserId` to pick which grant
        to revoke (`400` `missing_parameter` otherwise). Same-host alias rows are
        all revoked together.

        Returns `{ "revoked": true }` when a matching grant was found and deleted,
        or `{ "revoked": false }` when there was nothing to revoke (already gone,
        including after the host was archived — archiving a member deletes the
        badges they granted). Naming an archived host does not 404.

        Personal tokens can only revoke badges they issued. Naming another host is
        `403` `access_mode_not_supported`; omitting `hostUserId` when only another
        host granted the email is a no-op (`revoked: false`).

        **Access:** Organization and Personal.

        **Required scope:** `guest:write`. Personal Access Tokens use the
        `pat:guests:write` group.

        See [Guest Badges](https://developer.ro.am/docs/guides/guest-badges).

        Parameters
        ----------
        email : str
            Guest email. ASCII only.

        host_user_id : typing.Optional[str]
            Host member. UUID or member email. Required when more than one
            host has granted this email. Optional for a unique grant, and
            for personal tokens (defaults to the token owner).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GuestBadgeRevokeResponse]
            Revoke attempted. `revoked` is true only when a matching grant was deleted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "guest.badge.revoke",
            method="POST",
            json={
                "email": email,
                "hostUserId": host_user_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GuestBadgeRevokeResponse,
                    parse_obj_as(
                        type_=GuestBadgeRevokeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 405:
                raise MethodNotAllowedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
