# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class DeliveriesWebhookResponseDeliveriesItem(UniversalBaseModel):
    timestamp: dt.datetime = pydantic.Field()
    """
    When the delivery was attempted (RFC3339 UTC).
    """

    webhook_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="webhookId"),
        pydantic.Field(
            alias="webhookId",
            description="ID of the webhook subscription. Omitted for static (UI-configured) destinations.",
        ),
    ] = None
    """
    ID of the webhook subscription. Omitted for static (UI-configured) destinations.
    """

    event: str = pydantic.Field()
    """
    The event name that was being delivered (e.g. `chat.message`).
    """

    url: str = pydantic.Field()
    """
    The destination URL that was called.
    """

    status_code: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="statusCode"),
        pydantic.Field(
            alias="statusCode",
            description="HTTP status code returned by the destination. `0` for connection errors and timeouts.",
        ),
    ]
    """
    HTTP status code returned by the destination. `0` for connection errors and timeouts.
    """

    error: str = pydantic.Field()
    """
    Failure classification (e.g. `timeout`, `http_4xx`, `http_5xx`, `connection`).
    """

    response: typing.Optional[str] = pydantic.Field(default=None)
    """
    Truncated response body from the destination, present for HTTP error statuses.
    """

    duration_ms: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="durationMs"),
        pydantic.Field(alias="durationMs", description="How long the delivery attempt took, in milliseconds."),
    ]
    """
    How long the delivery attempt took, in milliseconds.
    """

    message_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="messageId"),
        pydantic.Field(alias="messageId", description="ID of the message that triggered the event, when applicable."),
    ] = None
    """
    ID of the message that triggered the event, when applicable.
    """

    success: bool = pydantic.Field()
    """
    Always `false` — only failed deliveries are recorded.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
