# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_webhook_response_webhooks_item import ListWebhookResponseWebhooksItem


class ListWebhookResponse(UniversalBaseModel):
    webhooks: typing.List[ListWebhookResponseWebhooksItem] = pydantic.Field()
    """
    Webhook subscriptions owned by this API client. Empty array if none exist.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
