# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_subscription_request_destination_type import WebhookSubscriptionRequestDestinationType


class WebhookSubscriptionRequestDestination(UniversalBaseModel):
    """
    Optional delivery authentication. Omit for Standard Webhooks signed with
    the API client's `whsec_`. Set `type` to `grok_bot` to deliver to a
    [Grok Bot](https://developer.ro.am/docs/integrations/grok) webhook-routine URL: Roam signs with
    the routine's sender key (`Authorization: Bearer` plus
    `X-Grok-Signature`) or, if `token` is a `whsec_…` Standard Webhooks
    secret, uses that secret instead of the API client's. The token is
    write-only — subscribe and list responses echo `destination.type` only.
    Re-subscribe without this field leaves existing destination auth
    unchanged; send `"type": ""` to clear it.
    """

    type: WebhookSubscriptionRequestDestinationType = pydantic.Field()
    """
    Delivery auth scheme.
    """

    token: str = pydantic.Field()
    """
    Grok Bot sender key, or a `whsec_…` Standard Webhooks secret.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
