# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from __future__ import annotations

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_event_calendar_response import CreateEventCalendarResponse
    from .create_event_calendar_response_attendees_item import CreateEventCalendarResponseAttendeesItem
    from .create_event_calendar_response_meeting_link import CreateEventCalendarResponseMeetingLink
    from .list_calendar_response import ListCalendarResponse
    from .list_calendar_response_events_item import ListCalendarResponseEventsItem
    from .list_calendar_response_events_item_invites_item import ListCalendarResponseEventsItemInvitesItem
_dynamic_imports: typing.Dict[str, str] = {
    "CreateEventCalendarResponse": ".create_event_calendar_response",
    "CreateEventCalendarResponseAttendeesItem": ".create_event_calendar_response_attendees_item",
    "CreateEventCalendarResponseMeetingLink": ".create_event_calendar_response_meeting_link",
    "ListCalendarResponse": ".list_calendar_response",
    "ListCalendarResponseEventsItem": ".list_calendar_response_events_item",
    "ListCalendarResponseEventsItemInvitesItem": ".list_calendar_response_events_item_invites_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateEventCalendarResponse",
    "CreateEventCalendarResponseAttendeesItem",
    "CreateEventCalendarResponseMeetingLink",
    "ListCalendarResponse",
    "ListCalendarResponseEventsItem",
    "ListCalendarResponseEventsItemInvitesItem",
]
